#ENC[AES256_GCM,data:/5bkaYtvcfoRoOnwWC1KcM0PzJcznGvDcHdIOA56leKRS+PH/U2MZRTBlmONPD4H1VcHfSdEqgXuJC92kbh2Amygaltn4zATTvvlKPY=,iv:ZD1Ojd6XcU9z7/lLtWed4NaKSZigIcTBnGVq02GsvQ8=,tag:2jF45iJovTjyySFiTdOO1w==,type:comment]
#ENC[AES256_GCM,data:O2+Cwd1pfWeuL7+HXIeYy97Ea/n0EnfUdAECCe3I7gPY5Hx+I+2Foprhg71mNlGiGEhunGgINYscl0iL3JnaMHjYJEb+dRayh7FBcj/WvA==,iv:xTqVuVh6zikM4siqc8GbIKTok0zPtB85Vy8wBvAZCsw=,tag:AvEsY213eGBpQmeEp/hzlg==,type:comment]
#ENC[AES256_GCM,data:0xqk/J/WwHR3tJZBIkSyU1VJEOqvT0tg72KDpCK0Ktjd5LzWLSKJh1vTvFc/FO6AKae+cQfQif8B/d9l9MuYJSgjU3xhS2F8,iv:Ze6GWRYV+8qJOvDa+9HqdDeyW1cNH4If2Of7flmjKu0=,tag:s+PLkVEjHGYc/Hj40i4Vyw==,type:comment]
#ENC[AES256_GCM,data:NrzcPDM07N0LBYT362EV1FbQocwKyTFnSPSOukQlr4NDzLbUvPV0wg8=,iv:QZirMna61nk0GeiKxpFShC1mIfrkBOdBCt1Fs7RZ7nw=,tag:g3dKMUBHfc02uZY3yyLDqA==,type:comment]
#
#ENC[AES256_GCM,data:ykI2hc0eKBxrz5SFYQZdkfn3dPct7qV1BRZTRlzrJ/YQNcly8kpPLeDgkHzMdbPbGbxESEvEydIykViG5m/szOqxvoz4yr9LNFk8mp5M,iv:xAksR7iIyUFiJyNywd9Qag2tjcCzIsJp1vligdmXnaA=,tag:UnO18LfgnJAT2HEG1r4bpg==,type:comment]
#ENC[AES256_GCM,data:/roa3S9YaCvI2xjK857ydZm3+skDSVdrpJTlaFLNSNQPVSAU58vyAzrtJ2ecoyaJEtVfzgiVAOXtTJ28xrwaDEOWBHuszvc=,iv:dBS6BHc+8d8V0vVnlkrslHEd6DAb22JLoNp7o5pk+Wo=,tag:c2hKg3VJ8XOtOgbkdGQJrQ==,type:comment]
#ENC[AES256_GCM,data:dlNnEOAS2B2T+lLMKS7ugYTfbOk4k7MFIystm/GOCbvwAie27YFRcjfglV49VA==,iv:asRYyX9DGP0UIlNENOz4I9/RBL8AMjttb0E1NC0GoCc=,tag:lfDwMONauj/JA/HxAvoCCw==,type:comment]
#
#ENC[AES256_GCM,data:GbzClcxkWMk8crdoNqM4XBtQUTIvq5QYuYlOpABQnP6/vYm+locpDTa95p+tH8WIjfIwTNF1M83dJHQ+qOUyJvW71GHowEo/cCrKjC/i,iv:vAjUkcMWBFvypa2TiXMGQBWNRUE5wbJw9kGlq1+1i2M=,tag:iPOxm1KK4OG8ZmPbpAzIeQ==,type:comment]
#ENC[AES256_GCM,data:GoZOMkYlo464Ufu5CbGuKPLVMK1Ge9bZM5KEVKo0kLfteI+R9K7wVkVUwm/rxBubU2M1V3FMDBD8KMHKALFl,iv:zjVwD+UuUWkQ0zeqY0gZq2kGZtSnuuWqRf8ZcoObK2g=,tag:uyw7FnoFdki7Sk3QVJmf3A==,type:comment]
apiVersion: ENC[AES256_GCM,data:7uY=,iv:8XhRzakAOxC7U5MsCU7/WO5t97as1GJth7F+VuVSNLA=,tag:B9cc8oF8bW/Cn3QBPIRYxw==,type:str]
kind: ENC[AES256_GCM,data:I5Cfnr/C,iv:yEeC0SehQ1hAe6KZdlg+NQK2lgoYuG2qnq7vote6Sig=,tag:i4X0nTyWZodONJa2jY47cA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:N5LrCFxLpZ+2ueAPv+PPWYAD72wWX49JPKellkhSwA==,iv:7tzYNOCsGtOeIXsnNWKs4isdSMccqf1jD60jq0tXbcs=,tag:tjvcxnwcMeuSbN7Nc9cQkQ==,type:str]
    namespace: ENC[AES256_GCM,data:wuBPY6XdlzwoCG6Hv7I=,iv:wG0o4exz16CAy1DrVUJNPkdKsisq+cEFLWkeHJY/oJY=,tag:mu6E4hFFbPk1XR8aEJ1x+g==,type:str]
type: ENC[AES256_GCM,data:RrrH5MXb,iv:vLDDGSJJSPAou0lb8wg52urgbPlt8d/T4E4VgD25+pQ=,tag:N5UX0MssdhVVK26YkKabgQ==,type:str]
stringData:
    token: ENC[AES256_GCM,data:BbFQv1pCOS0p0Q==,iv:+6n44YkBm2Di5NeZaCgZqkqXumq94dJmtw+ZWYvCRW0=,tag:jfe2VPhA5yMoZfgEcNNirw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYQ3doRm9rUUc5Q3FkWGhL
            WW1OK0Jla3lxdXdzRHRvVGN0NG1YMWxaZndRCkM2Sm9XNGViK3N5clNLWE1Fb0Q0
            M1NiWVhpRmwrcC9wc25BQXhCQ0JlTDQKLS0tIFZ1enRnQXBBSVVqdmJEbTQ5dnlR
            ck51bUIyM3JKTm1FbGhYM29jTUhHcncKocSfMWzt8vplr1okrkEdBVILs0c127JT
            zn30+dwiweZ2mzSVE7+/bVYjfKXi3AD6mnM7pJQrv0C5kRpN1rcosA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wcyzl9vjwakzxtxzw2qupn5332q7kpe8j4zyz434dcx2frqwd58qeutllz
    lastmodified: "2026-09-02T01:03:25Z"
    mac: ENC[AES256_GCM,data:oJDb3nmGF+K8thCveoLRdd8X+t3vGyrqZhp2R/VhLPiI+wOPGZig4922TugcYHnWiP4iZuBL1BMp9J10ns7RBR/+7VF//84vFHnIObGXfjL7wMEEJ4NzXBDmZit7dBSfW+/hbVdR4P5o8qRHJhHcu04qGZLxsjuXZoyZV3EwFKo=,iv:jer3CXUK7esHsJXLJgb7YUB0r9EWGdUuGVNsr+qhJlk=,tag:cfWgzW8IR1t+a9qhzREgFg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
