---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: home-assistant-config
  namespace: home-assistant
spec:
  sourcePVC: home-assistant-config
  trigger:
    schedule: "35 3 * * *"
  restic:
    repository: home-assistant-restic-secret
    copyMethod: Direct
    cacheCapacity: 2Gi
    pruneIntervalDays: 7
    retain:
      daily: 7
      weekly: 4
      monthly: 3
    moverSecurityContext:
      runAsUser: 65534
      runAsGroup: 65534
      fsGroup: 65534
