apiVersion: ENC[AES256_GCM,data:Vmo=,iv:O8aFnOiQ54Wuet/x0aZCVGhzrfGMoc1Rg6zF8lVkC3g=,tag:ZGFW2Xv/FvPZnnAN/HTsJw==,type:str]
kind: ENC[AES256_GCM,data:SMyxUc8e,iv:MM5GDWT6G9uM1wLCVul74RvvDxmff1xaGUuuZvaag90=,tag:rW2jJfI70+KxzODQvz0+Tg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Tq9Xq3qHNzcmI8cuGDIyuxP1vXOkqS36kU2VHw==,iv:2LqtVmTDYrDiGyYCO23/7NMbZSoPjuWBZVYpMGPy6x8=,tag:Jenjhm5Lw8YJ68zSQXTzZQ==,type:str]
    namespace: ENC[AES256_GCM,data:nD7IOe7JhBrM8fwahTg=,iv:TDfkKxVnzP90JH1BBq2mYq+IOzgLtZLZl1fbSmet0Zk=,tag:0BKn8esE5trWj1j0lm5+fg==,type:str]
type: ENC[AES256_GCM,data:M47ZfkIK,iv:2ROb6T8RuBgaWDPp2ZqYZBI8NFpYVWnpiFCur2NBEBQ=,tag:AEhm9znYlYlg20vbrDELnQ==,type:str]
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:sioPXxDQ4ff+z/NKkAZKWYcmKRWsDqKDQ+fxP0fFC2+nyaEj+Dv3wglhQDv915R2Ag==,iv:S7cBjdlHUJ+63enjCp6PBku0TRLge4mx7mfI42yi66M=,tag:H1lisGxjszQy5ijHVai7ZQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:sA0Wqa79TZY4hxAPpkUh4n8E8GZfHFeHA+pqcss1b/t+s/7nlmgFpB/yYYegj075rf5StMT5JlW0ohLM6C1U/w==,iv:BNc+FInQGmBQrzF5yvcN4vBXCSWK/y1nOMhDJ2k1IrI=,tag:Teo2vqcW4Fqf0K3IPZWMyA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:1vzJvt2nmqmny0BVSiiWz7Tj2ig=,iv:BmpLsgwfFHLeD8aafFvdyhenRUfJnzE1LcwAqSCsTP4=,tag:PuwqUxZlqewgS/s5FmKFKg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:FVIra+0WoOGuzFW0g2DGfE3eI2GwfvMGCktd5G+id8B5+z+tgGoK6w==,iv:ixaBvV1x/erVFCMoLoFiL1ySzuEhxF+YqInzfCYCODk=,tag:sgMWZPt0DUI8lueTq3XK8A==,type:str]
sops:
    age:
        - recipient: age1wcyzl9vjwakzxtxzw2qupn5332q7kpe8j4zyz434dcx2frqwd58qeutllz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXVW1veFRmMGxmSEdyWk1J
            ZjlXNjJnaDk1ZFBybEpIUk9Vb1g3SHl1WUd3CjBHcHg4ZXVYOTNJbGt3anBGR0RR
            K2JjNXBOKzZpTS9kZ1BCVnlvNmUvUFkKLS0tIEFRQkdqNlZTZ1JSZjJpRFk3SEdi
            T1BuOW9Vc0ozcUFlRXVPb3o3NklwK1kKXr/yboyw3rdQkKz2lTDIn+z180l7ZZU6
            wRMKDgQUIMiW+sP4QQrOcPW7/sWmz/U7xCV6GKYQxV5k/gV8udmbGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-27T12:17:41Z"
    mac: ENC[AES256_GCM,data:yUSocxZlf8dUFk/faOfNKzwu+/e1j+dyuFLhvEksSA2W7ZVDuBVH6veVt4Ht6SzCNx7PTz12oJTJ4D+awcZaOJMJJiZoLDH3QAAfn894liK45ZOf3MSQBhzCdk47ZUxm1yitVjwgait/wCzchXS2Dt2HizslCMiPOvlhjnq8SR0=,iv:qcgEi9H5i4DZTDwolbpM0hegHGZM5JMn5CyKsM1YNEo=,tag:72X7H/53p/MBUqmP6EbEUg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
