apiVersion: ENC[AES256_GCM,data:gaI=,iv:LdajaVaOxe9akrb56jXoRi6HFTwSj+u1hD7ZnjGLO54=,tag:+Cvj9xw/A7Xaz7kfeVRFpQ==,type:str]
kind: ENC[AES256_GCM,data:CXzeX5Ka,iv:jJxY8FBzuQvbG5bXkBguZRsUBiz9HeImmbYihwcDy3A=,tag:o+1G6BSHdedDt7ROwXrMZA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:KeTkDEDL8QFmLHZ9GtsFZtHHEFA=,iv:3Ox9zngDve0BQ4DAIXAbfERxRsCck/sVFNECzjLTIec=,tag:aNTIYirKHbMz+Hn3aZogCQ==,type:str]
    namespace: ENC[AES256_GCM,data:KuHrelxa4A8JS3g=,iv:1T+c9uL32E8O3XkigNHzVF7glVJA7AfOXOfepsIz4Hk=,tag:/hTODz5AsirTAJNKCnZ4pQ==,type:str]
type: ENC[AES256_GCM,data:0zl41xWj,iv:j6n+nTHg2V62sKLwfVMRBxFqg0DSxazcKp/M+NB/lwc=,tag:cyfUsVZfI80LiLA4Rxqzjw==,type:str]
stringData:
    access-key-id: ENC[AES256_GCM,data:Z/Fb9wVBuRXdHRuNKJPID00NeoU=,iv:7arZoMTxoXV7Fdj4qxBm2QkH4EMpHtd/jNmocTSxnU4=,tag:MLacfTAMmm3/Gnju7HDRrw==,type:str]
    secret-access-key: ENC[AES256_GCM,data:dMHpoQUqNjVndy0+qSldnHfTUzjzWJKTrdtSpDOY3FIxNTxjLKYjkw==,iv:CmmmkfrjMf2JHPmqvwZ2I8UQllU6A+81Cy/I7kIkImc=,tag:/RL4AsxEmqV1kvvOp12aLg==,type:str]
sops:
    age:
        - recipient: age1wcyzl9vjwakzxtxzw2qupn5332q7kpe8j4zyz434dcx2frqwd58qeutllz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCM2Y2VGluSGphTnlQd24r
            b2dEUzI3bTdZS04ycy9hQTFZQitSellyWVZBCmpBZG5KRlVwaW5sWEc4aEtQM0th
            WlVDcmhtWXR2a3dHcmkzZUpHOEdlRncKLS0tIEkvTEw5SHBJRThpRjZkVDFPN1do
            UmpGcDcrM1NSZC9KVWVIazJQMkh2Z0UK+UAWp+I82TLHeTxBCZVa5tCJjP6J4Hjd
            Pxdg4dKo3L26bEBNBOw/yim5wAfkjv1Ug2xC9iG3+U3+12Vb6weFEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-24T01:15:56Z"
    mac: ENC[AES256_GCM,data:CCYq3xIvYsIUPphQELQWycDcHme1RZhN6k7DubCePddmpOcDZP3ipsJ1H38B6KMVues973rKtnDeUge4Yo18Ohcq04wCoJBepBJKyyW1u3c64c4OL12r0f8yT+FfEJT9saXC7dTr32qd+zLq7+kOFoOsErVs9bTm3uYEaB0gclo=,iv:IrDfr7xZLXbGBcEMWMi537XuMC/6l+9WrHUv58Y+/Ac=,tag:WPAk4y3PKfXxt9AaiTiOow==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
