apiVersion: ENC[AES256_GCM,data:J1w=,iv:wwKfiJdhjmkOgtegXVQTzXl5+jzRkpmLJx1LobnNJ/s=,tag:AZWbDKEyh0gCrTCVwcQ17g==,type:str]
kind: ENC[AES256_GCM,data:jdDcs3G9,iv:saYKfFOQgKVMc9ozYRbUx1j1xVg1HY6L4zq0wvf6yRw=,tag:BK3ccz6g0AcbvveQkSqKAQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:+TJm2JQxjxREYhp1jIKokIPMIQ==,iv:4PuJDnbsrXGBPPXVaqh0+ZGMGd3Pt0dcy0mvqpzoaRo=,tag:BhRh8f6uL4lYUZPpVAuYXQ==,type:str]
    namespace: ENC[AES256_GCM,data:tVMrP2LH9rlayOU=,iv:pQ4kOWRY/gp+rDfFSTGJFWCm2tytZt6OFf2xbhYlx4I=,tag:trCMJv4NgE8OdJb74c+8OA==,type:str]
type: ENC[AES256_GCM,data:RIyfKFlZ,iv:hqbOwF71xcxAlmKKhOufKH5Zw27FH6SxufdPnzYxyeo=,tag:+ULydYqf6i5L5K7yAGCtgw==,type:str]
stringData:
    root-password: ENC[AES256_GCM,data:g+2kFT6n0XiAmOOP2T3QOd8S7A3aTi2Ao2qVeRFq6LI=,iv:5W7YvSCOJrZslvktyukhY7Zpq9nnYKU3L2XGsqbkOkI=,tag:eO00UbG4QqYN3/x7/IUK/A==,type:str]
    app-password: ENC[AES256_GCM,data:74mV8iRC7YRdfXTQtbWBpGIeCyHR4WsBtR862CdRbDE=,iv:yjUXWmrSM5iPJXSwHMi1YVjOrBVNNOqs0kGslLavcAw=,tag:VDDV0JLCYzkcgUWh5JNqjA==,type:str]
sops:
    age:
        - recipient: age1wcyzl9vjwakzxtxzw2qupn5332q7kpe8j4zyz434dcx2frqwd58qeutllz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2emo1RWd4YXZDbThsRWdG
            UTJlS3FVMklod2x6bVZGVzBleUZHdFoyM2s0Cks2NFNnUXRYVDg5L0hLb2JTYXNp
            TkdOdWlVbnVoY2cxNE1SZnE5WHlleUUKLS0tIGlER3o3MEJEU3dmUmcvcnlhK1NT
            eFhrMWNqZ0ZUcFo0QzZ2TFE3Z0c0NkEKDtB755hMG75A6mrw7uD/9Rv461zm5SDg
            caSNAoQxm4wU3pKG63fsZruLCH9Geq+aGyPjC2/1UmotXFiqgVHzSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-24T01:15:35Z"
    mac: ENC[AES256_GCM,data:pcc0EueSTutnwI0P2XSBK4hrXh8BtYOZRBSUQXQeWgB/JtY5mm0pb7LyobegBwAeE9jQrCgiYTvCxEhc++slDysylmLfeFrqDgAYAFf6g+yaAW88hKXr7EiR65+439CdtpLYYH8n5tBqVqysncQIJd0UItV2owricmDy5s1egGg=,iv:qVAY5bkOrJVvjX3PRGsvP1L8oAf2Lsu2vQC/rHUCz4w=,tag:XPljnn1ioowRTi8O8pz/bw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
