apiVersion: ENC[AES256_GCM,data:1zA=,iv:VjpkdF0IiOEmK2ZEkdPE0Nxnus83pLfmaWMo376/cts=,tag:NeAkgtXojluDIm+WnQ9BmA==,type:str]
kind: ENC[AES256_GCM,data:p3e1fXS/,iv:krKmaGly9YhfH11L1uHzeEcGnUcLRnKgaAPZRPWXKHE=,tag:8qURc2J0SfztX0t0+Ghgng==,type:str]
metadata:
    name: ENC[AES256_GCM,data:P6XdORvYhfQnM4iSO7U=,iv:Hq2E/c2iSAZSOXmOqbM9Uq2/isHXul1TRKaipsOF3Ic=,tag:Oxkhcp1o0M7/jnIyL61VgA==,type:str]
    namespace: ENC[AES256_GCM,data:bGDVhSwSMg==,iv:tmQIr5faAHi0OnWmMNOJnvP5Diaf2vHtROXN8m6IyMM=,tag:IhF+FIL0jzDxfw8RoSw2ow==,type:str]
type: ENC[AES256_GCM,data:fy0U7Rpu,iv:4gF20ZZpDwHDvTLJKmWVAPDZ/yMcwwNbh9kNLG/o7bc=,tag:P7b6A9EkJ2UBJSNCL+hTVg==,type:str]
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:5znHGCHGx56gfljebJ1ciU6vvjlPEY2Y25ktA5ZUhSUyDcfZOuXInPSqS3TPc3m1gfmufMCUIzTsO/cwUTPOhA==,iv:naLFfLBcO+R8MRiAWKv3tPoAVF6qprLvgkcWu20BfCA=,tag:9TcE3ewlpVRDscqXhSrfOQ==,type:str]
    SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:9iR/otMw1/NOv6kX9Jv2GMKseFVs0/0uM8rAzzI7r1jsJdJSQ19Fm+yqU4Ey8zKrBkFeXbRBIqMAKd86+HuRBax2qbyZOEInSltiPjUhDo2y4kAFQwrGqW2OCOqkYtL5CLOaU+fbU3/X+GjYoPe2737ziNgU/XgkGmhi5ef9Pjf9cKgY1dFWOUX9g2YzcCw5hIrAByHj4c4gukSWkz20bCn7JBaoLqErOwAd/q8yfwHfUjHYq+QWAvrJ7QHXxx45q1ltihnR7gVoewPqcw2BHVn7ifh2ln55nY/xq7JKndwfojGVihI1ieO0uBNSorIq5AIt2WsH10QlZlAEimOA2c+QNEkH4s+y52TSSHEgKg/38vJldyWK5YIOTUrDLiEYVwOy,iv:rqv5MpEvvki02LWXj+x5aj6BEqgLHwpT3HEcZLpgpU0=,tag:5gsJBzEnXuo2f4T3r0eQGQ==,type:str]
sops:
    age:
        - recipient: age1wcyzl9vjwakzxtxzw2qupn5332q7kpe8j4zyz434dcx2frqwd58qeutllz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGWC8wVDlkbVpqOHNoTXc0
            N1ZHWTVUaWllYzlINFl3UVRvOEVhVHk5d3pvCmgyU1lUMnVkdE9qTUJEcTB6Yk04
            YzRyNTlPUFVEYVFna3k5WTA0R1ZlT0kKLS0tIGhRMDAxZ0lCRDNMSGJaMFNKUnVo
            azNuL0hYc2RLSkR6UnZiU3Y3SW1lMEkK5V5B3LazMxSbcXo+7J5dYB6Y+UNLZ7sZ
            Bl5ym6qqNHdoUqHVjF51IEJ3m9//niB1PD8SK0TUcw/J26u/MiEEuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-14T19:51:59Z"
    mac: ENC[AES256_GCM,data:/Ywl5pSytm/YeujA1iSTfK3CMW5t7DTy4kKXNv9merwtaJHFiXz41UbhVjbQL2DIwOx6R4VIopM0xsjwv+j23lsIKRwIWCn4RzuFriydzBZfwjySlTkZyvV/HYiZUkNRV2kFC4IE4D376n4Ivfq3VR7zK2DYpRM/slL9ZW6zU7I=,iv:S9s2gRRzCAZdqvIz20zift04XnHdFftxPi+lg5e+GSQ=,tag:JBbumxNYSlMW8A9TDA38Qw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
