apiVersion: ENC[AES256_GCM,data:4CY=,iv:YgeEQDX4AEfpk9bZBL/K46OKWEwBlrdNOujq9WFaA3w=,tag:YD50n+43lfIzSQdccTFVMA==,type:str]
kind: ENC[AES256_GCM,data:PSOzFIuw,iv:FOZNDyn6nVAxPb0+VbxnsDOHaRfq0BE+Lg63X8GJ3oo=,tag:oOvo7k/S9lsCEWfE0bnBpw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:MmLIzV0JPKlnOsO545uAVAfXzZnl,iv:rHU2qV+kCLWN+hvzy28nqxL0sncZ9UxbJ9OaWvxRgFM=,tag:Ahd85T9fq1FAIUhuvY9Tyg==,type:str]
    namespace: ENC[AES256_GCM,data:u35dMsvllg==,iv:OJ9O/vIGiPhGG8ap8iMJ5ESEJerKUREow/3JXhRi1t0=,tag:EXy2p23y1u0RwfD6/uacFA==,type:str]
type: ENC[AES256_GCM,data:BCqv0MnE,iv:LsWkeHikQxS/cUn4GwhuJEABCiTJl4yZNBYdtpUyvHo=,tag:/TAeD6Xm6CWdYoVNpmx2Lw==,type:str]
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:UlJZpL4McEh3ZpkPXfr7liYfdCYhga6uIldw+Q==,iv:+/GNR4WF3ce+43AgmjF5u336gdPmatpMHhKFnh19fv0=,tag:NSAx0wF+xiCPwcCSG9W9pg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:V3m8dHpBd6PSSIxJRlEdGGj1vZO4K1ld8XIxCx33KTibtWPP9nilraGRlaeeBqjr/I/Uhr6CMO8=,iv:IFiRbHpRyx9sMJulf13ts27tNq41wFvhY0SNgUJ0n4w=,tag:x05q2u+xPtYf5+Swv6UOWA==,type:str]
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:8dalk0rGpqgfn0dNP1CSol9i5eSaPhdnUpiAZB33B0gT/iQCblz8BBot,iv:CYi9YrkIJHQTmPGMbvjfkai46P8DP/Dlvvu6jYMGNTY=,tag:hq27wPaqVuQkdV9dJqFf0A==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:koE4MRc/fnNOgZkTk4oaHvSaCs/9byJdPTsyrksqLN/WBLKUc5vE8TKCjU3DD8Yx,iv:hFpY7LtXqMTZAEY/y2a9HyR9aQU27at8t1NABuaT3+4=,tag:+X3KPnMODpq/UcDxy+TNEQ==,type:str]
sops:
    age:
        - recipient: age1wcyzl9vjwakzxtxzw2qupn5332q7kpe8j4zyz434dcx2frqwd58qeutllz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5TytSVmlOUGdJL09mVCs1
            OVNtUFp6dGNJTlpvT2k2RTlBcUt0aUZzT0Q0Cm9PZXA5ekdHb1RCUEpmMFdma1JY
            OUJqY1psMXFwZ3hRcWoxMTRUaDY0aHcKLS0tIExZUVdsa3o1bkNuWFlEa3d6Y0tI
            aGhQUHgwMFYzSDZkbk5ZcFhtRENpL2sKB4DlEAfR4M0dyW14oweQyGe/fscdU7JZ
            BcWQKNp+p1pKvWi31yLrfSkOzNRmBEFgPRSzP1R3RWucv031j5SLxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-14T19:50:00Z"
    mac: ENC[AES256_GCM,data:FCnQov5Ik6YMnd384U9zTbtI7/tMuvsVrFR58cDFta4BgDRvlOUCAFNDM61sPi0G/Z7+eABTrsp4/qJv1vgnrQ23KLAkajOZZ2q9uGyxSNXd0UgngKo4bjwm9OEttK/XfmyP28vY+2j/6WRTi6hMQ4Ii0MOWX6kkT+o7akMvI+Q=,iv:9cma9oV/OsJsVjeKlopjYPRkinKu3wG5mtWDIIN8eBw=,tag:P2vuVmfjmpQizo+yOk/N9g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
