#ENC[AES256_GCM,data:qsCs7145JcQPytcJTGFEGRcvG9qlI9cF4hV7bhVhk/ERHQdSXObfeB71T9c5IvnCpLR+oSLRY89qawX0JZ6Evh/XDx1+hYaTKH2cbgF6,iv:Sc3Nt5YQGlwU6PhfUcIxGX1DCVIghdbD8AcBDV5cuSs=,tag:Mb4LeCE5nhxhaVDTLTrF9g==,type:comment]
#ENC[AES256_GCM,data:nDxOJd5vF5qiJ57eL2RWwxrMqQhatGm9OpIeD0Zb2XEcjKicBx5phmg5ktSi7I0GqREpsDKGrhCNEj3c2UDM1WQ=,iv:F1NsORXTEPzPJPPnDVPAbT3qeoz7y6KfLuDbomwVx3o=,tag:WxNMlt67b0NDehdRcQbRXw==,type:comment]
k3s_token: ENC[AES256_GCM,data:BiNLe7SGmC29WqV21ue8bQ24qX93OrBX9OZc6qm6iPGhlNmCuMY6Hoqkgu9LTOQ=,iv:RhbJz6wk1jeh/CqCep9HzW6/Jjhb2svfGRVRQzNMzPM=,tag:CR+3U3gMcRqlN5Bd8a9Q5g==,type:str]
#ENC[AES256_GCM,data:c4MBPO3ZIbhW+fnSdSKBAHs2nsWJPw9NvSK86ofv/yBZ+5Aq8t8Va+V/Kwxg5nF6MpW3h/auKpOPLCMw8PyGNxrjaIeEWIQDl3qpwYQS,iv:Ui+RHKyaXuR0euysBt+6vID0D0422LNJvsphb2Gg1SI=,tag:0/nJ+gfCC68wXdp3nrvsoA==,type:comment]
#ENC[AES256_GCM,data:7JD8vs/G2NF0K5+XKE3DtSXKGALtDJotyBecr0ybuiYSowQHG0Vr+8+wJOR6pd7z8YdzXpNpPbS5Iw==,iv:tQ0vqifAPvxA+capVEHkWKqCVfd3+ogDdfPfHhymGBE=,tag:povpKUOMoR+Q7/O4fnROMg==,type:comment]
vault_s3_access_key: ENC[AES256_GCM,data:4/EnCMsk4t2val4kYgqlNF0yYps=,iv:bd4YzpRXsc15eqXp2/5VR6Rzc2kjsETdJbTVrO2Dy34=,tag:bXcTH84RkJLzD9My+EVuMA==,type:str]
vault_s3_secret_key: ENC[AES256_GCM,data:CYrqYAlsZYh12Hi9N44xOL8fuJKTqaiaJV9+3tKKsXn1D2/mmJow/Q==,iv:SzwH0X585fg1ni3UaZkBR5COJWCxd0YHVTYiL/33gwY=,tag:zWY4xD/nPNVR2XPWKJaGmQ==,type:str]
sops:
    age:
        - recipient: age1wcyzl9vjwakzxtxzw2qupn5332q7kpe8j4zyz434dcx2frqwd58qeutllz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBldk1UWVp0aWxiU2owQ01i
            NDRoTzRUUVBUWmxsYlJmR0xVcDBuQlZkTHlzClk5L0R1dUNhZS9xdGJFRWpBcVBO
            OVZOalY4MmVpT3BqYXRsREVKM0Y5bjAKLS0tIER3aDFNR1R2ZWtzNG9aMXZDbCtX
            blZVSWIwTUV0MzdOMTduOE1aZUZyUkEK0LhfbXsQdvuU/Xnop4uCEvGQXAmAsFt8
            hw7uObgJgVOWTchJzcH9XAB8Ha7UcVkk9ym4tJY4VBWHWfi4Umzxow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-23T22:21:34Z"
    mac: ENC[AES256_GCM,data:osDZDZ2Pc/X6ZC/1oPg7PSPOwpL/DyQyp2/crBMyDYf0CAewmM9jI0mhDzNQ3nK7IhjZycibMiOGETPHBKbypdTFUST+Mz3vUr/WiZi40fIDbVsuICLKJviuCKHwpDshf1u1JcZOEjiZ/hwpsgjoew6H8yo8ZvGTDZikk8xLr/s=,iv:OaVSvPVta7E1RMmhAI3ENRRs5YMfiM+/xW9wVa8cj0g=,tag:pd9MjrnAEnq59lDOmCjrNw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
