---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads-nfs
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 10.2.40.10
    path: /mnt/mainPool/plexstack
