---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - nfs-pv.yaml
  - nfs-pvc.yaml
  - downloads-pv.yaml
  - downloads-pvc.yaml
  - sonarr/helmrelease.yaml
  - sonarr/pvc.yaml
  - sonarr/ingress.yaml
  - radarr/helmrelease.yaml
  - radarr/pvc.yaml
  - radarr/ingress.yaml
  - prowlarr/helmrelease.yaml
  - prowlarr/pvc.yaml
  - prowlarr/ingress.yaml
  - seerr/helmrelease.yaml
  - seerr/pvc.yaml
  - seerr/ingress.yaml
  - maintainerr/pvc.yaml
  - maintainerr/helmrelease.yaml
  - maintainerr/ingress.yaml
  - tracearr/secret.sops.yaml
  - tracearr/backup-secret.sops.yaml
  - tracearr/postgres-objectstore.yaml
  - tracearr/postgres-cluster.yaml
  - tracearr/postgres-scheduledbackup.yaml
  - tracearr/pvc.yaml
  - tracearr/helmrelease.yaml
  - tracearr/ingress.yaml
  - backup/s3-secret.sops.yaml
  - backup/sonarr-replicationsource.yaml
  - backup/radarr-replicationsource.yaml
  - backup/prowlarr-replicationsource.yaml
  - backup/seerr-replicationsource.yaml
  - backup/maintainerr-secret.sops.yaml
  - backup/maintainerr-replicationsource.yaml
