apiVersion: ENC[AES256_GCM,data:rZM=,iv:NWZWapVvTAoNEtEIr8jPuyHfDLo8kF6sKoCdoTbqKvg=,tag:05mSu/2jm3Os8FIZcNHXvg==,type:str]
kind: ENC[AES256_GCM,data:0E+/SuUk,iv:mEpI4OU5P55hzmxdHXsh1LrmTwkEURWzq5yPZdl6FXM=,tag:fXTrdskHnuZ4aDMDqtK9vA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:M8yfG0vh64w3ZHahqkA=,iv:cFtwxfEkj3S5aMiLPXRu/ihU0yii/FzxHgxaa+leDr4=,tag:kHAl4X2520UP7EMPDaa/LA==,type:str]
    namespace: ENC[AES256_GCM,data:3vSgKzBTBe78,iv:eogBZlf9A5LtGkJFHhJDlq4ftuM77bhVedLYd+7VKJA=,tag:WhTL1klU8wvV+YYnFdbHaA==,type:str]
stringData:
    #ENC[AES256_GCM,data:B6X5MVL2m6ABD5zUdPoahaFav4bQTXEie1PZOvNQvVmODAGdR5Q4SkORSJwZwIvHecSCGcT/KkVuGeTwwZ37F3zq4us=,iv:qvZJkQK0ArY6Oc79XT+IEx0LvUwk5WXigElx/VkSB5U=,tag:3gMeOD+7wBRmuY+pG697KQ==,type:comment]
    #ENC[AES256_GCM,data:iuh6w4/wJZIgUEZ5nY9w9KBykl9R368B3GOxE0wClFcEcsD53wYoqfzaSmHb1+dGKwVmV1vdxttZB1VNIqw2qJiB9SQ=,iv:MFZDWvbUc3cICW09oPFmwnjyybQpT2MXqOY2pIgK1BI=,tag:DUBmV8xrJla2++tF/vVHMw==,type:comment]
    #ENC[AES256_GCM,data:QDd4iSTrE6zJD2k5hgOpTDMgRO7clUvUIVolAqe4PjTYQ5u+WD+0V4Ssh9BC,iv:0X0Up3JhemOMOPLWZtkqrQ1ji8AgCqr9FNWg2NdanzU=,tag:TzXg2v1xTvD6zytWSHUztQ==,type:comment]
    client_id: ENC[AES256_GCM,data:xvH/uAS9k6e8pIyTAN23YfjXUzDLOcz4/ZdJYg==,iv:zuOEiP+ekCLwDINln/Q+gByQl4Wlml3QBmH4Rf+WBf0=,tag:M9sCod25+VEULHLaSbFEmw==,type:str]
    client_secret: ENC[AES256_GCM,data:uM2QA747grnNqildO++qV8CkqpNSzbCNhK1AWWhjciw=,iv:nI9f6Q25mhTMTcnrKhhmjTfZCjpUhSe61a0B4oH7Dt0=,tag:Kg4u4/4wW/hidi8mV/iyrQ==,type:str]
sops:
    age:
        - recipient: age1wcyzl9vjwakzxtxzw2qupn5332q7kpe8j4zyz434dcx2frqwd58qeutllz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArU1VnU096V2ZEOXU5Z3A3
            TlpGUFN5NnB0RUYxK3BqTFVqNkJCVVkwRHdVCjN4TU93SlBIdVRYd3ZLSVduZ2Iw
            Q1dYaCt3RUNOd3RDelJyYzVnWXJpWncKLS0tIGgwT0RsQnM3UTNjZmtIUGxLQUxu
            TlNkNU9QWE1JM0V6bmVIYWZ1MlZEVHcK/PUa4vBc8iq4YoE8Y2nVGqYpbUA85Nku
            tg98rc/XY0+TOos091mLui+EsfOeZOTRE+ewGI8WITI/LJIJZ90hlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-02T03:01:50Z"
    mac: ENC[AES256_GCM,data:6qhGUBTivklNLQebVikODikCtLYRjp9Bl8GzLzy8ApyxSpmf2RzZLKAUoBp//NdKiYc3TlwJKCgrE6lrNLH0H8h1pIc6VR7/mXq0yL27llOP9O3TH/Hy+YtLdWZtFGvm60XEbsMHHvCg/ZcPyALFKjRCsH2QqdUl3tzJ9IOTue8=,iv:1vGczM4qHiYHO2Pz0nlU/lKHMvmJBsuFsa3WnavkLx8=,tag:b+msC7nf62dVTnzL/5lZ/Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
