apiVersion: ENC[AES256_GCM,data:Ykg=,iv:7pvPbRnf15TKzI4/J/xNDBI5JNbhb6ou74rr06ts33w=,tag:hfFN3SdmORSLXgIUR4CDFw==,type:str]
kind: ENC[AES256_GCM,data:uEnyj1n3,iv:gxUMBh0lHRhDuVOMW/Rz3O/mRqZBRhz2VcEy4VbppTo=,tag:vA1UYIWK/uEdao2dvYcEEQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ryEXxkFQs+rlYjkdysymDA==,iv:SVDThebXMoGFxS+6qQk6IGCVewPlk7e7L+ruSh58g9I=,tag:1xENqtJpVAbmPbma/QFbdA==,type:str]
    namespace: ENC[AES256_GCM,data:LFWindniybmT,iv:6PdZ2XUEDB5SoP5prbMgGHgTxSm7QNUAEBS10OlH8WY=,tag:cap95Iq3XuIjw1TQSZySig==,type:str]
type: ENC[AES256_GCM,data:8SnyDkba,iv:9I1MFeyKDfXpaXSrhbWGRScI2s/oVaOiVCM1v+ROPg4=,tag:1H5McgVZ6Y7533yik2mZKg==,type:str]
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:pdMLikwmLs7QW/dD7MzLDD0L65y/ELmt4ZLkfOdBzvB+TmbxfWb5GNnFk4iShnJUrOzVJ+i+w/kkSERmk+HirWgvDkzrreZfd70fehHHF34=,iv:WFrtFQ40K1CYqbNJZx+SHyZUvoUgn6f01jOGMk4sPQw=,tag:1Q18clTEnpHv7k2iGtTgqg==,type:str]
    GRAFANA_OAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:iVAcnLk+t6n7lBJjm2+GszC5S85fGKqeT71qbDY0TUmsK4XOiQ0FZGrL/eofCScc1BUZoEEApciY5dSMhINe+A==,iv:EpVL66AiR6uGGN7b9hBv8R8DAGaFxbjdNNiXkCtxs/o=,tag:RXLJ/dZdupoqoV9NpAU7hw==,type:str]
    IMMICH_OAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:v4LtBig6rqjK2qAS7XBWo2oc6/fKEg3OQuQq0kWpRNKOY9ejjR/2jqPx+WZGzwmKgXHfSEl2fRRjVS8syGlKRg==,iv:VgLLXosaU9L8JLqduOoG7rRgSOZm7sUuzqBxlCYIC5I=,tag:3amvA49PXrI1GDsqSQY9bg==,type:str]
    PAPERLESS_OAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:O8wdaDzua4qPymaQVRvt/NhX3jTWlMInwdZRWSa6RqnI01TElUpQDGKS8SvXsil9CSXb/PLDRHnL0lGvAScvYA==,iv:BTPr8g/G+1Qx4ev01qFlsBl0quReMZrSnWQftkFGhpM=,tag:n3U//j6toZSV6ThHSFesYg==,type:str]
    GITEA_OAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:S32mjktRewZcLP9a8bi01ZF26PRvMoEJjNbfmzKyQsujhg24PPB+mF7axkjKNKVaBtQLse7NgulgGKXCGsPFRw==,iv:0IjRiWzWKhptMyFGj9h9tEiRwTKOq1hC/t6M9Bk4l8Q=,tag:43LTr403z5iIS0QzKjPbFQ==,type:str]
    TANDOOR_OAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:2/JmEyhIdSvRhncsP4f8e/6U3eM+r0UCRF49LD0LsXbEHO25q+5IGGPgFJ5ynfzYAS+lSjBjgX0/rjyiwCiVDA==,iv:DGLb5mCJ7QLYDUnhf9oc5kizBpiwn4CakYSm04CyMdo=,tag:WDy9uNL4vgUSeyLP4h3bFA==,type:str]
    AUDIOBOOKSHELF_OAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:lKiIoCPhJlET39n0OOnNrpPvv9JVYuKpoRJAJyXmTRkFCOdzIGcgYrWdJXe9nRZw5Bx2k49B9j7NNwL7wTzg2M7+SMRofgmrmg5ecY4ggOg=,iv:7Sd1m2lfrtvKi3Q0zAn8U3cQKR6Lgc9MuvCOpshF9sQ=,tag:W7HUTD0dF7e6fjRRKFW8tg==,type:str]
sops:
    age:
        - recipient: age1wcyzl9vjwakzxtxzw2qupn5332q7kpe8j4zyz434dcx2frqwd58qeutllz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtMCtvWWVMZHVGWTJNY2RZ
            cVVJdEVJV0xOSnhUa054ZFpoMldiUHJFWFE4CmpKMTE0TDNCemIwSFUzbFFCZGlx
            VWU4a1h1d3VNSTFPZnJROEh1OWpKdHMKLS0tIGZBWXk2Y1JRMW5ZWjFSa3NNRll6
            YVpKYmVwSUd0ZDIxQVExRHJxdmxmSUEK1F/qfbOitaASfb9XYKgU5B20XMc7wRLT
            zlDSo8D3yGm23AiEqujUg3C6c3WaAyREc3Y3a69PX6CNiDDG8BfTPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-02T03:01:47Z"
    mac: ENC[AES256_GCM,data:V4Rk1Om4sFwENUeFcgUWha1nQG6XYlbh4iN7Biqvs6YnacroJHRflOJS5aBgfoy/D3sBj5WRCuMVk9Z8Up2Cda8YbC3+x8vEQXjyuGZM+fJOW5A/khxT7xGFs4fYirf0KXdRGJMTsvZBCdLW/prN7nRBQq1LSsCuA2ppBqzC+n0=,iv:LUJi3gxrClmvSQUQdRei/JzSig6+nnhIy1Low5f678c=,tag:wfJkZD5kRi4bDv9ukCkjWg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
