apiVersion: ENC[AES256_GCM,data:lII=,iv:AKARQP1hJ25p5IF8VGbrpr/c/kJ8j5sgkS7UXAAOlzI=,tag:dtRI7DVJRqI16xUVGYbD9A==,type:str]
kind: ENC[AES256_GCM,data:keLbBBIX,iv:Qi9HeVBWyGS8jbbPCWvVxDlh+XeL5Qro5FDOmffSj6s=,tag:EKQlRLnszcx0stVtEMil3w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:xKjm5I5wj8mq9o2tOwWnpA==,iv:QffKE1dccsaKxTa7Gfa5VFD+Kja0Q6iZjJt2pBAYwUA=,tag:8AgYNd1fFUOnUt+rm2CgVQ==,type:str]
    namespace: ENC[AES256_GCM,data:42Hhqcf9B8Pq,iv:tc8zug4482SnkCgnCgTJ0m3e97ByeUb6SOFareEo0g0=,tag:tQnmHDgLwqK2fbG2MKVR4g==,type:str]
type: ENC[AES256_GCM,data:cySFLmyi,iv:nkX64/KpXyOLkB039vjoNO49Hb47yAUgbFwxyRecT1E=,tag:Z13KN6bsVEA5rc+Y67FBuA==,type:str]
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:wNQuX97mk1fr/0RwtyklCEg3IAYTIxUOqV166ch30gL1SVLYLs3UfTihOrBcPLZ/zUWom8IaVOewxqmiC1MDAUTut5RHhdTyRaWZtrzBEco=,iv:kbe5pLXFCDttn9GwIolyBLRM0y1y7kUlWOulgYP+P4w=,tag:PTLVvWEgCJT4ANMF743LuQ==,type:str]
    GRAFANA_OAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:sdp9OaylD6s/O76SeEOTPsnJsvMBzDgSJmFokBalnoP76JdaNtvgJMSsp+r8SJgEleJNMu6LJ1fiSQnSZeSxVA==,iv:VUaZs/iuR7dCMQdFJeJZZVEsqjlgNwS8CTScS3Je8Lg=,tag:ik1wVUHdn9yAeWV1Lx/zxg==,type:str]
    IMMICH_OAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:RW0aeGT75H8tqZmBE5z/VYW6dizCMonaPvPa0Yj7/YoKmpo2U76fPPayaZFvBhvimabCxWeDML5Y7Y3/4oYh/w==,iv:IUDOfZskEVW7MJrjWbW2jXOfIhKuKQCf1PoH5q/6PkE=,tag:xBDyB7l83D4//fqZcS/bJg==,type:str]
    PAPERLESS_OAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:D9JWWe3QniEHLPKJk65meS4hCO9ZTVJyZOxUMKXOtfTrPYPWkaSSnW8zIrwttOldByWob/ifP2Nb8mlFx52jqg==,iv:36fhI4jZJa9tcFy9c8LGYcGTg2eZfCIy/KT6JIuo9oE=,tag:Huj1R10lFSs12HDiwFeLxg==,type:str]
    GITEA_OAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:Qv/4rcgFA2iHy65ciIGbAdTr7WFdEP6+KdzSeCqr3T7SA7Oj1ZZM9ZMF/bYTzDODGS+PAei9HROmzvkzI4JXcg==,iv:0xUl0ii14ucZt0/UBYb6sJeLUD52v23nbCs+zn0zVL0=,tag:gmCtM0XL2K3MUVzUPT2tyw==,type:str]
sops:
    age:
        - recipient: age1wcyzl9vjwakzxtxzw2qupn5332q7kpe8j4zyz434dcx2frqwd58qeutllz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJbVFkamxudXltaDMvQ0hp
            RG1IcGxwZTJ4b0o5OHp5REhXRGxrUzhMUGlzCkx2V0RFWmhrdjdDbmhXeEU4aEpT
            QzR5d0VaNXpJUmtHTmZhM01pTXV5YU0KLS0tIDcyKzloK05xUHdtbksrMUgyWFJC
            UFFjTmN0cVcvaWE2eFl2ajZOZTc5YTQK6IvodUqSRfwYlPLZKgXVu1ca6d3M7/+o
            TI6sqmZQpaAbwWx03y/tdEckS+Md1zP95PPZ/eSx7j8D7upVm9YsPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-09T12:59:51Z"
    mac: ENC[AES256_GCM,data:DFiwr0nap/9jKC92Lk9PNlKz6epRFHrPkvVY8s8Upt/4O/eQbEqwLo8yhBSNYUD8Qp1J00RQt/qn9qdoGR8Wule/RTnZUQv8LUAxpIjujr1YL9ewoReYtW6e0FS2/jD2ajOdqTqTUvB5puCUPpOeBw96FHj1/0xTdrENO64XmFA=,iv:mPGEnyI8VUSxUEJJ6wCyHBRYv36CSdxLrcFhz7MWMCo=,tag:h2z5X7Fj6UxpgAmlbADT0w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
