apiVersion: ENC[AES256_GCM,data:bcQ=,iv:vpXoBLQOYvDAwVHpMPuhiQ1yBiwYtCms0QlBJHH5uJ8=,tag:ESkhBJEFl7K2zdIbwCySBA==,type:str]
kind: ENC[AES256_GCM,data:d0VmPM5Z,iv:aqnhn9chF/2MWzgdOP8mmXc0UzpzZAuP7FKX7PftdP4=,tag:XPZuq/EKjAtjZvM8eo9+tQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:HbPXvlNouuzI5HXrd8a9Sg==,iv:e7TlIGBb48wBRyHAOQmeUApGzHshHoQII3+Z/ruCN+c=,tag:m5T41esuGCJeo73DUJ0LWA==,type:str]
    namespace: ENC[AES256_GCM,data:Yb99mk2KcSOe,iv:mDeVr1R+GpL15r6euPig/pg2+rnWhCG0d4e3+SfJLPs=,tag:X3a3j5Z/H0atf5EtvxHuwg==,type:str]
type: ENC[AES256_GCM,data:GTUj6MGY,iv:djSOJ1nc6g39nGS66HeFbf5TFBPRIzzcpzmwZouO404=,tag:BHbs0ZAbhO50uXgTMOOORg==,type:str]
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:5v/dZT/P67jrcvaBdd/4qiSOiXmPQgSwwVfxnub2lAZlVU0iDzHCL61PEfY9ruu+rfBH6UsClthd/Mz5FgQSrPrp04Yu+I8ZEt/k6jdc7/s=,iv:GgtfYVzjLmL+7vPVEY2h/mBApkx938N8bVfFeV92VhY=,tag:/L18R0w4/iPd4PES+h+bwA==,type:str]
    GRAFANA_OAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:VMHbz7NJqE0+gE+2f26ND9l9Yw4taj12q8rCME/utUKdF28ggFFfOG3MhqJfMtWzCdEvzlBWB5veISUsRHyxvA==,iv:/Sxble7FJ6kg5AavTBv3N2Ni4AHzF6ru1y3yO03mB8Q=,tag:vc4HkgCgy0IXjvI8vT26+Q==,type:str]
    IMMICH_OAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:N2qyXL3ZouBWD+LGxiPvb6LO6gyyQqFvisjFtPNdWStBgORG6LlyBZfWHNCJiqd/BitSBCQLLOhUV9p4cQqsxA==,iv:zoYkGz7O016+7Crm6b7NidIeCGdDnDdlzGfacHLCmkM=,tag:9yQuFjEA8GN+AW8A5y60jQ==,type:str]
    PAPERLESS_OAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:WHsMxyGT9XHdujCkw2ssHVgZ33jWOIwdn9sxgYLw5WM3o2VeeywE9A/RnWE5i/JZqZigS6siQe2A8g1wx24GUQ==,iv:wuQK1DcL+PJgxbKbjsxxQLSdZt5YRuomRiwPVXtKnKg=,tag:dxGDZTuno57AeN8Cusbfvw==,type:str]
sops:
    age:
        - recipient: age1wcyzl9vjwakzxtxzw2qupn5332q7kpe8j4zyz434dcx2frqwd58qeutllz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQlFFUUNKbloxMUluaFhh
            S1RXcGUzY0s2WlpHZnlHK1N1eHlxSzJmMWhnCmhBanpQbW1zZjdtc3owSHRLdHcy
            bm0wQTRNNHJRdlVXQnlTNTUzODk1NkUKLS0tIFBuSHJXQjB6TlhiVk5LazlkN2py
            NWNYTTAxWUN3NzE5OFFHaUtuRzdaMWcKF6hQI9PXaH73b2yrDyQ3w8tACMNK1PPa
            Fhk96nAT5XzJFJ8wWeDf+OfjnVSdpberPwggXALYygY3sYBOrTDXaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-28T12:23:09Z"
    mac: ENC[AES256_GCM,data:4ax68gDaocsD2m2WwLsXQgNgeGDioZ7xjMe56+PcI9S9kJlBrNBRRqQslxcW2DhY78OtrAkxpfao3OgHDqsbRjpoGWCWCpwaGDrf9nWYv4Gjr2i/aLjW7caiWUkOPNKe3e0C9rcaDyRySwNdwJ/yiwr+Gn1CV4Uwugq0pIzJty0=,iv:hmE1zCa+5TIFlIz3Fw6905oQd9DdQLQIoJo4Vb+AQ2I=,tag:4Qu7z6SmEW4a7LWRB3Kzxw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
