apiVersion: ENC[AES256_GCM,data:sL0=,iv:Eajmtvl2kG/Ft/6wHakVee+dENiU5IM1TNOFqApehCs=,tag:aQUDtsvq1Cib30g2fiY2hA==,type:str]
kind: ENC[AES256_GCM,data:KIekftdO,iv:WS6MMDbQs7rrTe3yEmktEBS2w76PuM4sMBpFYtwmOsc=,tag:qvk5/peK8muZFqbwQ1o3Dg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:4iO3hOy7fo0XKEUvrVF3nQ==,iv:uxrSfjHEbvZwbukoKDUi13aFl7Kc7BujyCjswp/lHkQ=,tag:RaFYDMpa6f7soO3oT5x72Q==,type:str]
    namespace: ENC[AES256_GCM,data:FuM/ScmXJ4gl,iv:a3SZ/xntDNx9lFLQ8dL5Mr3394dk/fzY7F+AnD0V9kE=,tag:asegduivaQhFSEr4Qe3ywg==,type:str]
type: ENC[AES256_GCM,data:P3hi+eoy,iv:s9kaItGNOlRseR2tTiTqSZjZV1WGl2gI842wGemeJtE=,tag:B4Bc6dgeh3hLgs9bJ7Uiyg==,type:str]
stringData:
    #ENC[AES256_GCM,data:JiemGU2s9CGNuJ6Uf2LIg2U5QaSitdfp0hSKjMZqr/gxBIWbIepQaIPCfbqkluMnnWzRA196yqpjn6RHycOHsiM9k0eqHIPtetkhjQ==,iv:hC5E3SGg++PjHyZ+6PQNbJgVRGYMJyXSkaF4YA+q8po=,tag:aNNnlvMPl8EFUGdg6W/slQ==,type:comment]
    #ENC[AES256_GCM,data:4OwuGEwNVgVVcHOUXqixOueZG8Lp1YMeGGgGDV1MRDhDlEKZKqbYBz85tp0cK6r49a9v/tHrZbUM,iv:Y4wLIG8Az5MFzVUu0Sf4RLZ3wb2U8VP4s1lPkNm0hFU=,tag:O8B6wFE6t1WxLGLKAPYMTQ==,type:comment]
    #ENC[AES256_GCM,data:iBFQyLX6E+/b1yxMDpbODHtFYQGO2yVbBlwRiEY4/+a/jrNfnhbGy4XxFA==,iv:l261DSykz0VNCJ2b6yHwSOj1bjk0AP+KP9Lb1uTTdJs=,tag:uxV8ItGlkgboTSyNAr7rqA==,type:comment]
    #ENC[AES256_GCM,data:2Ebti6K/Pag+IKEJf4KB0ubdJY1gPvpbE2uKZT+33E4+XzqTVbI8g0V5D2acNLseDNWOMhgEK9bIR5twAJ1D/zFLYJWfGS5sy65DRwG5,iv:KCKN1MEn+c8Gy2VGQD+aDNVdJAaYd4Mq3NuXDBjJe7w=,tag:Ia9U+Emot55Mat5qWlbTow==,type:comment]
    #ENC[AES256_GCM,data:BeGtJ2TEat7T1yBRrzkztd80DY7RSzKxjdpkH9+lC2PAey9ytdLOaEilvtcMvfB9lM5r3/rwEFX08KkvPDO0qEPDGWrw6GI=,iv:C3Ta508q0yMTKbc/YOS2hHFiFwB3y2hyhnt8wLUi06I=,tag:QgG+u9rOtxGkO63xez86sg==,type:comment]
    APP_KEY: ENC[AES256_GCM,data:VnYJwOrL5wLfB+rmrTYHWGc6OJ1+F+Yyz8SSeO3eFI12VTIeJ7xtqNOBem0YTpr5BJti,iv:Pk2l5B0IMMZVPXF/H6uFjftr3j6AJ96FDXDz8x/3X/M=,tag:k0f43GHDa5Rl9smoIlVsQw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZFNNTUpQVFlzZERBZ1dy
            cHZrSVQ0T3VzajdkbS80dTRFZkI0R01CdmgwCm1PbXZRVkdQUjYyb0NDbTE0d1ZU
            YUNmNFRUT2l3V2lrQXh1RUxNaHBIVEUKLS0tIEd5K3FQTi9ERkdISklSSEF5VHpP
            TmtaSmxQZkV0TUY2akNwRkpHREVyTXcKKWWURmQLj0qEXFIb9SQaQsN8wTyOomjz
            gd3GBCfjGFmvSx8CDhmIkvTMsfkHwx9UNjdEVjoa+b2/dOuYuV3GWA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wcyzl9vjwakzxtxzw2qupn5332q7kpe8j4zyz434dcx2frqwd58qeutllz
    lastmodified: "2026-08-19T19:51:14Z"
    mac: ENC[AES256_GCM,data:f16t+PU9OF+0prkUS50hUoFGc5laV2+YIW3Sqw/nIrDhwAWq7j+m7WxI80E9e8rdUnK/a+DG5TRXmJeK8Q2eXWqYTFOSimp2N6CFnsdBSSw4DsE+hx8aXOkesbymuuhBWsaPTun36y4inNUvivnqB8Ws4D2Tw6TKEWPTp/ecHWM=,iv:I2Of4Y5B+yNPpe1BtQCkTDKo5PmDLKcjy/uEyEzgXRc=,tag:h0a5pH685GXsYAhTwo1w9w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
