apiVersion: ENC[AES256_GCM,data:YH4=,iv:NyTSz/cbWLaE/OMlAWS+Ad/oaktQLUyWqf50SPKL3qE=,tag:X7FbSemDiRAVDpq27bRKQQ==,type:str]
kind: ENC[AES256_GCM,data:QkDRYtqZ,iv:kfhclS8ql4WyeP/MiwyGPzP1kex2BoOa5yEmGRZmFZ4=,tag:4cEza02/sAu5S+cs7F4dww==,type:str]
metadata:
    name: ENC[AES256_GCM,data:9zY5/mdphWhmpj/u9AKi4g==,iv:xGSv3U1tsEdgMuMukEccaetpT4GA30oMVmEnJME1J2k=,tag:8LheCQpCujtcVx3O+wjnSg==,type:str]
    namespace: ENC[AES256_GCM,data:fWZHdmo=,iv:SfOwsfLQDsVSL3PwjC0c8Er7rc9f58l0OIlrgUp0ojs=,tag:GeEBFG4i5UEC3WAaS1KTxA==,type:str]
type: ENC[AES256_GCM,data:UMVWfNYl,iv:CheGFRFw6rcIuzUBsemCzJenRSrBrUq0cVskvP1MgqI=,tag:gkYTF8hfKfNtCfUk8mKeVw==,type:str]
stringData:
    UN_SONARR_0_API_KEY: ENC[AES256_GCM,data:NFcC5+e3m5QUO4WxSHB9SHtGsA+Kev2vjwEQGWEJq14=,iv:HVb8+WuhK55ZP8zbuldqLuwTy1iZ1cy/b/O4XJsKMks=,tag:yqQJ6jauVXjObGYpseBMtw==,type:str]
    UN_RADARR_0_API_KEY: ENC[AES256_GCM,data:D1loCiG5gKTY/WztDJWk3+xJcEolxRKp5NsDXISo6Mg=,iv:lieKpgmyRnTrBkdl3ceBwk80VOWgTCyZGMCni71SsBA=,tag:RJV2rPi+w7PE57wSBud6fg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmazdYTDdxeTA1d1cvVDdU
            K1kyNHdEQ1BCUzNOcnRMbUtEWFA5QXEreXpRCk9pbFpNT2p4ZldJSGp5NlRZckRj
            QTdHSjFvNnV3T1VlZHAzQW52T011NjQKLS0tIDRJRFBCSmtiRm9uTmdZMjNDeFY2
            MFZYYkJ2VTNSc3B2eUVLK2FyY0NBOU0KJlNGd/OxS56Yzc2eVK2j4K0egGZMZ372
            /wwJUJX3jIweSbhxccN2ovHpWIAaNpXTKDDub++tE+5mns8KyprPfg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wcyzl9vjwakzxtxzw2qupn5332q7kpe8j4zyz434dcx2frqwd58qeutllz
    lastmodified: "2026-08-03T01:18:23Z"
    mac: ENC[AES256_GCM,data:LzT6om2lv7CnyL+mA5nLP+zG18ilUtStOf11LZ2sTgxZsv2X/33nxf0TJtkFCNCs5TU7vlpRcLE8oDoX/AHvRTji1b8S1T3FuH4Mk6LCZLgf7rxFZWCWgb4IG9WpK3SzKfJKuvskb4TPTxCkOboGlmkLuvdFWPJVXSqKT3jov3M=,iv:87b3pVzncW+sMUgY/ZIQjHnaRykiecfejkKFd/rUAVc=,tag:XD1V1lWzGEfyXLnlMRQAcg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
