apiVersion: ENC[AES256_GCM,data:1z4=,iv:qdfHtJVHGaysmrh3TBpKsWWlaI4MDWFiEpCfUcMeQP8=,tag:LxsVCrdvt2MHiWFqwUUJag==,type:str]
kind: ENC[AES256_GCM,data:gp655vuC,iv:7ghgV1ZvjcKDQWDE6RAQ+6iOz4PqpeafZNCxbqgULlc=,tag:fKg0WGF23r+a0J8hFQtAtw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:mGZvnSyrhAacvCJKD8e1P3/zX1WL9sxO,iv:Oc73ZHpFzv+AABG4+GGkXisE4XpMhWRRUdpq2IIdXKo=,tag:HTPu1UntU7s9S1g8hgkhBg==,type:str]
    namespace: ENC[AES256_GCM,data:cEGgjX61UuzFog==,iv:CLy5Qdvz9jgeUy8oWOGQbDKpuAAgEyUf+nyQdxDVVKw=,tag:/dFuVW430LvYhLnIvg9J9w==,type:str]
type: ENC[AES256_GCM,data:yaEzvA2T,iv:OUQcgJx36Y+tOkGcty7XYwFYnpgNQLGdiwt3YdkHxBc=,tag:lOejtUzngoC4fBlqReAsZg==,type:str]
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:GVCsIHGcGKyfZ9WobCFJrrECaXVqa3p1iZd6eQ==,iv:URpXnWKsW6jmbQB6R9YH9sfY4e+psxTJOyXU8dWIoiQ=,tag:iUMTe3/2s38jMRNwmnj9lg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:de+BFlHAA6vhNjHA24vurFInS4+FRpDGRp96g7CTa3WScJJvJ/CgxrmUzczMJiUdTgunsyL6rhA=,iv:sghA3pVf63kXwi71mwizow48tc74jX68V9pi03CUMOI=,tag:WsThHYhM50NfJG2P5Gm5XQ==,type:str]
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:ASo+yQIkJp/v+5tShlik7XO6m5gxY5DXWBlDJc3keQQQD0PEfNM2cxmHMytY,iv:Ze9VJNzf0F7QdiauEonkEZAQvLtY7DcTzps0L7JKufY=,tag:ozYNBn5QEWGncKKWS7b4bw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:s+8z464/RzjD+j1V67lYCUGcVBO2pGo8kWTcN7wGYbjeAPMamRtOJ9rVOzQ=,iv:mqrC4yOFfRPoVpw9GjuFnFUOjhysmoA3K3z8hcIP+EM=,tag:Mw51i7CzAPSxh5uf6tbpRw==,type:str]
sops:
    age:
        - recipient: age1wcyzl9vjwakzxtxzw2qupn5332q7kpe8j4zyz434dcx2frqwd58qeutllz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVMGNPTG9ZM0Y0OTBMR3Zp
            QTQvRHpUK2lMc3hLVnFlVzBIM3djZUJHb1MwCnJLY2dIY3hHUXo1RFUzelAxVCtY
            RHJZcGkyQ3pUU05uVU0zcmZ5TFlTVG8KLS0tIGxwelFEdDZubzhtY1VMYUJ4MEtY
            enE3aVRsaUlGa2RsVWMrTWRzYVplakkKRCHD10VuNSaNqxkciidutrV4jBwDMMV7
            lpyNsxQ4Enpjj6+JEQv9XjKUESl/4nruvE/0LeyLQLV82VbC4Io14w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-29T21:14:46Z"
    mac: ENC[AES256_GCM,data:LPNHSUx6iPHiN1VyflYwwCmz3/sXys6/JsWNPtlIY//Uhk3KNnnggXmY12T6ea6ZJ5CAW6OFhwrQhp/Q34WYAffJl6VuUJ/sDm77TxYju6BccmqInYe4Gbzz0uj6RVB6rlEyor/weDZnft0vaNWIn7ghjZ6wxRAYqoEh4y+JTOs=,iv:hr2EcSiS5AaLmH9SnskHtHDgFP984eIsDPIbZyWvuqA=,tag:rfaMoQEoI6YWFUE6XT7aJg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
