apiVersion: ENC[AES256_GCM,data:CdA=,iv:UTpGonCS4aTSuisvU23U/hvuVYuiHGsYq1QpjoMaYSs=,tag:h2/uFX2pIflpku7N9aksLA==,type:str]
kind: ENC[AES256_GCM,data:gTM/XXwo,iv:T0XpAnTAZzvjzq25CZuq6l4peZHFEmqPUAiEmA1z5yA=,tag:n+QWg4y+PmrfD60E80c1YQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:uc8gnbORlJQsncf+6HvQJByt,iv:cO+qtF4ZnM6r9xZ9nCC+MzmZgFSpfR4lBRe3M3na2Cg=,tag:PeBYI7XN9pok/cd6eQlO2w==,type:str]
    namespace: ENC[AES256_GCM,data:aLgTZCpuVZ9bvrQgKJ4Q,iv:N7qycgJ6jIC7AGcYlyq2g+NRfNFX6/z5kj8SgaOl9dc=,tag:h80UvVPqxkyntsTPSpfVSA==,type:str]
type: ENC[AES256_GCM,data:B/3xkWUE,iv:Wp89kk5Zn3F3Dav2uKbCkhT5Eh9wxJ82HW2ZSzFta4A=,tag:ui++2X0jcgsNxfJGziX2Aw==,type:str]
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Bgvkkl2cYJwXX4O8A8KmGnm87kI=,iv:4aMO55mEtddFIE+m7jP2EUrlQzNXuST0p7Kc/y96Mpc=,tag:rfzQ7F7J1BVg9w+lqC1xVA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:aMEvMs5n8fOUGa1L0HvGB+q3TTrjCiPgcHmqrt5znhxymfYWXPWX0g==,iv:SloMxtJ3U1sB22E+/hOdrbtbiUsnmL/CnbIt5mZRdo8=,tag:YbI/MRbiplwEN0Ajsw26yw==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:Y2AgMnvmQ0K5gs3xfiiO6uzH31Yz7Oc=,iv:8FPMzMjNKqCQHUKnqBWC6HrU94fJVS+oovICE7Zkyuk=,tag:I1v88SGv/nsOHtvvhNJCDw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4NmpOQkFINTM0VUtoMXFP
            QW05Tko5YUZqY3Rwb2ZWWHdHcWFGWXFJMXdVClJrR1JjUDFMQnAvOG1TalFMMzZE
            WFdLRUd4VjM1blk2bERxSDJhVjVETlkKLS0tIHJZeW9tVHdSZm9GbkR6RFpHQ0dC
            YjU5VFAwUjFOTUhaYlkwUUVlYk1kYzAK4p972zWcG31e9ymaAxlKyNbQ/+9cee33
            MVZn8qa29FLMINjZh4TVCcDpR4FY8wqb62tA8BOIBznlEtQDrM0SlQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wcyzl9vjwakzxtxzw2qupn5332q7kpe8j4zyz434dcx2frqwd58qeutllz
    lastmodified: "2026-08-05T18:30:19Z"
    mac: ENC[AES256_GCM,data:XmoFvVJbpX9KlkXy0qgL+Ki6X7scbMFUPEFNVf+4eNqsynQRJYWdygorYhJl6/J6jwWnP1KD8yMjZxtKHgGETS6+bcCplGVM5gn2NtD6yhXv2ykz4UC2Qm5I1KUHBhgHJqj5a1Gv4ooUeCRhhBI4nohPfDVeBiNNOidZtt1ctz0=,iv:qTIbGAV8NBeJEt7aBHQPQkGuM7QOb8zj27Uh1x5BODE=,tag:e9/4/3XRPZmiI/mARzi8+Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
