apiVersion: ENC[AES256_GCM,data:/AI=,iv:UtqNQH0Ar7g8Z77ObIFsax4wva1DFEiW1UODLGisYgc=,tag:kuzulWO65Wtv0okzVhRp0A==,type:str]
kind: ENC[AES256_GCM,data:+qkBgFYC,iv:vgb3xCkWfg3AA4pai66GIhLsQ00RXVL+/TFmBnVsNM8=,tag:vPd4rQR7/Fncg+sksIm5wg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:T7GRk/ZKh9mnArYLCByZuYyu2WgYpw==,iv:zOt14E1anFm+6v/vwjFlx4JeCCiNl+keur14m+XFd8M=,tag:+EGsKB9cNK4gAdlScr4z0Q==,type:str]
    namespace: ENC[AES256_GCM,data:e3SbIa4=,iv:AO+xrj6AzkdP7juZuiTggEym32FC2xKASLFAsIo+cyw=,tag:0uNulbqWUx1MLv0XCWOx5Q==,type:str]
type: ENC[AES256_GCM,data:9xpxpyXW,iv:MEpOamjukS5BqC7XnsI/xrkLziGe1FWhf7qiHilw4fg=,tag:+OqELEbqtVtD6f7uc5/4+Q==,type:str]
stringData:
    API_KEY: ENC[AES256_GCM,data:6AdZyrG3+HaTIQR/VrKTQIhwgkNyHWdsaFPtn2DPrOI=,iv:WX2ET6UIqjx2uHdCUo/MaG6F0omtj1zzhmfdAGVjCZM=,tag:mnzVzZMxy3KGy5LYZrgo+g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1R0dsSzVSNUlRUGVjRTZy
            U1BlWi9HVUVoOUdvbFFidmdYRDRudlF6bVhRCmVwWnBPbHY1QUNRWml4ak9lbzJo
            OUxiaHU3d21ScnRHcGg0UmhsV1lsVjQKLS0tIHhKcVYvaU02Qkx6a1FPVlBOMFVq
            bDVhS1dtR2VyQXo3bGcvc1k5RG5aV1UK4+ZiOnDR3E8NCQtuvo7hI+HWYh4IcbtC
            KN/1c4lvbfoWD8spXUKMCsbmC93kTyXpzsNydNt3Zd8IbkeX+LKlwg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wcyzl9vjwakzxtxzw2qupn5332q7kpe8j4zyz434dcx2frqwd58qeutllz
    lastmodified: "2026-08-09T03:13:45Z"
    mac: ENC[AES256_GCM,data:TE2n5cDNeNgRj4nfvLpgvfcfuo3JI39b6HertoSKlfsPJlo2Kok4CdbMpZb8zuFlz4MhabAKqCh+KiqFH6cm1auiV7OzZlzvNrmJItYLqIW9jnKYWTGl8qvsjsKdFSt0orcHZMUn8tYyXACyE/RJI/lnlBkF+Nncy9NaZ407c44=,iv:4fMY8Ob2KOdaS6zHqUEybx/79oiL2EE2ZZlx3GUVB0s=,tag:SAJN+8YcCNO6+mmWmJrqMw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
