---
- name: Reset k3s cluster
  hosts: k3s_cluster
  gather_facts: true
  environment: "{{ proxy_env | default({}) }}"
  roles:
    - role: reset
      become: true
  post_tasks:
    - name: Reboot nodes after reset
      ansible.builtin.reboot:
        reboot_timeout: 3600
        reboot_command: "{{ custom_reboot_command | default(omit) }}"
