#ENC[AES256_GCM,data:7SKIzqACi4/zH9j/hRtH4N9oipNQTLNY3qb3XMlKCMgMvuqfQNClJ4A4fNz6NyF0g9Q25CgzH/JaNdk=,iv:vU2ArMcSP1b+cEtDIxBpKbcoc/PWa50iC1dgCj3bkNU=,tag:0An/ADISTXWJyfBdaDVEEw==,type:comment]
#
#ENC[AES256_GCM,data:RKM8RiF4Nksnpm1fKh7s/PsHtrYNWObiYrw9lBEXT+0gABtXo1A0Lqi1jzk/0qyzIWFgTwU0+RoxYL1wg2jjsmTZE8iWTtK01fLi1A==,iv:xZFudx1i9HdocobeywQMNB4lHJxxay90kf/ZvakQEeo=,tag:1npBdkT+1emUkJ5hSh1Uxw==,type:comment]
#ENC[AES256_GCM,data:RoBbaaEsqxLtrPdTWRqhI0lWGr0LkWhR2LmfD7h0VKB5jNiM66Lh7fYeMfSRfzyRNzx4rFdFi5OdEE/+GejJRxYMwWVaUpU+SoWH7ps=,iv:LRW+v1e+YdW7d03CizHQS9YF6ciRdc1gb2O8nOJGPfI=,tag:Aan1eX5VUMDB76aGvUEDcA==,type:comment]
#ENC[AES256_GCM,data:ADvmipRxH6zSG1rouUsGmvfhDvjap4ljGsU4R10BU1jDYXfR7JBiqRYX2/wPKR3E8smMwWkmKpDtykRKG4EC/n1qV2h7+qHD,iv:JoXw5F6hW13RWH0iI5+LxR5k98HpO0+wvy83DEsXg1s=,tag:y3UZzQmf/NsBCzU4Fjr22g==,type:comment]
#ENC[AES256_GCM,data:sN7/J6rAP4oiZuWGcEuUF2cn61zaMVoqP8F0sA64ubdtkwACGTefiVCbzCF1g3FDi0mL69ZEHHva05cJ9ZHTxUOsJ9E0Jx62etoh2IynZg==,iv:9fW0LdQN9PSW/YIyAzzgCCuSw7s9U8k0G9atTFh32S0=,tag:/PduxnwOB03j4tRQzqcJNw==,type:comment]
#ENC[AES256_GCM,data:Kptr2hnCN84Dh9+8x9Ch/Ok/YBouEbImfbRx2+gHwtZK9W81QTq2j2hDwFM7l42CIzKVu4xwc9hOtur4WV2bvLdfZBijr7kVQidf,iv:uQytWXCWqBV08kpNkEc0BjBDpp7pOsCvKUnpq4tmceA=,tag:TUnTPhBJjSSVOJifGUXrpA==,type:comment]
#
#ENC[AES256_GCM,data:4ByWufk8on0oU63m13J4EyzZnLqanOeXk5Io2wBaUy+rKGsWj3uwvRu8ELR290+o3GRUkIktGJnIwDKA,iv:AK0Tbj0xz9u2ZPNsRuW0VL0FEZrRqaPigAaRxwiFLV0=,tag:KckNAjTr9ybgstd4gvXYqA==,type:comment]
apiVersion: ENC[AES256_GCM,data:efg=,iv:H4NPYYuCARAB8Nn5MSf4UtnOcBINXBSbRxr96XURUJ4=,tag:vor3hdwqJ3Ad1+re0zOJnQ==,type:str]
kind: ENC[AES256_GCM,data:jrdOPdey,iv:uV3rg8f1+EAbQbrHfGaJBcnFCJmJ1CW7Fziswh57p88=,tag:MJGqZgrK11nYzpn0QjngaQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:acfJ9xA9oKB0w7swBevT3vXN4g1/Io3weQ==,iv:VNcAwinMKuk7uurqLyvwfOVz1J+6bc2XM+sSwzkY8ZY=,tag:Zu3TFiplE1AbYt5xZrDQ9A==,type:str]
    namespace: ENC[AES256_GCM,data:e6YbIZ8TGYN2Gg0=,iv:q0ZyotFqQiMPV762x03cy30emWiPLSjf3QO+cDcdDy4=,tag:OZu8mJpVQ/h512rXr7tRWw==,type:str]
type: ENC[AES256_GCM,data:pWMk3FEE,iv:MOllJXx8lUAIVmFXaMHZG7m9eXhMsiE2ZW05JiZgXMc=,tag:9hZr2uFBIyf6oZ8S+DwW+Q==,type:str]
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Lmlo2r/w0Lo+17SeFSohrIRPvFlFXjtiG2WUwA==,iv:07UkiOqC+5p1qZmFQUNJKrMvBR+Gly21+95fOCwjHnQ=,tag:uXchtgzZbaMb7rppVwx4uA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:OJ9GIndtmLZducFJfd4421cjABxRGJYmGftw6/z/qGqf3nGi/frkieNVRhd8ukp2Pvoqb3kIhtw=,iv:7vyK97cOwD62EonycuD99V+4HFkhvbPIj8OavYEWftk=,tag:fJt0WK8NZiC9dv3Megk0Ug==,type:str]
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:41Fec3chCcukoIt2gJYY1Qq/w1qRZ57OFaMSjqlXSCTyRHP+pWafip59BC0Sng==,iv:IUWqbqEcTZlHF+FUMKvhOntFhVL9J0y53gwjTbsmC6I=,tag:kH6mjUxsyXHn3OQ/r5w+Qg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:70GjScWs+W2R8w+9EWlimgRMvpookYHaJ1xo2Otynx71xsyvK2FPRD/4OqBxrdxT,iv:nSZE4nJIdyyM8DmqRZlyKO49PaevIdLRo3gGuH76aSQ=,tag:wPU+JCVkkZg5BbJaqIVN8A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VjQ4Z3NVRjUvajkyRm93
            UWo4TUkrTklNeWJsQ2l6b0pkdEt5VGtSWkg0Clp1REp2dllQek1BeVI0N1dHay9l
            b3hITUdsSDBnNUVZOGlvQmFOOG1JeHcKLS0tIGRnVXVaOFlrbW92RUM1UXpiRkRy
            ZC9MbVhjNDZjcVlIWmYrbGhmeHNEdmMKQ6yfZgc848y6MihnWas8tajp9zAhaJgW
            0IgDTB6YURrFR1WttMrloxPesZglDc0Pxy3n7lzOEpVE5QuQVZC4Vg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wcyzl9vjwakzxtxzw2qupn5332q7kpe8j4zyz434dcx2frqwd58qeutllz
    lastmodified: "2026-08-31T19:23:21Z"
    mac: ENC[AES256_GCM,data:zjMD9PhX8w1VOKF1P0CRI+vOtLlLyklIfXG8hSZyKnxkVSCyKTdU+tLO7bYDpdqHm9QsIiWacc+0KS2LWtqvveO/T3C/XeZ8j3TFBwyfZWCrJOMfyLKdVzpWImRhtPYXGAvZ3uRbK0TVtwrrkpw1KP1Z07uPfeN+Qg4GKny5D88=,iv:w2ywWJDSAnZADvdlVAY2oabPM4VKW8Xfv667pZWcL8g=,tag:WV7afqBoKOIZQ7cjpukL3w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
