apiVersion: ENC[AES256_GCM,data:D4g=,iv:JHCVqxoKlLr7KOjXAYy75z5/VUM6TJXeJVM6cI39mJ4=,tag:YVjobnPEQDhBWcRWLnneQg==,type:str]
kind: ENC[AES256_GCM,data:egnOkOTd,iv:eFTx+wDasZM9hezo2BwNcOklleaiVQe68Z4RYwjOtJ4=,tag:dFhGYBOv6ME7zAMVKGk7RA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:h9bq5paCYNS+zEPnICSCtQgidKgiNm0=,iv:SalVZzesak4a7L2iXEx70bKD/0fPscKRp1+lXthIZG0=,tag:hSKa61qdnoQOPy8npSq3VA==,type:str]
    namespace: ENC[AES256_GCM,data:gjHtrOI=,iv:EhnFiPcJGBGMquX1NmSvd0z5duSMzgvbUlHJdShil4I=,tag:ZrOuX3tmaqFVAHzgHsEBMQ==,type:str]
type: ENC[AES256_GCM,data:x7rsERC8,iv:KUbg5xgTPN2Dtavhj9FA1n6jM4sKAoKbow/VS9e8P9Y=,tag:DqVX9lCxTlAU1CwdqVkdyA==,type:str]
stringData:
    API_KEY: ENC[AES256_GCM,data:7JRa3N2RN0JFBswtQmO0kquuVSLKMDs4p2ULnLgx0qQ=,iv:0eEsv9nfkUbL+rGrkPf1ZFV0Vpf2tmJgL8KiMsIoZjA=,tag:bLGrDNabHq8UpHkTfwbcVQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0KytzM2YwNkJuNGNGeEl3
            QitnbDFBSi96dmEyN1BpOXFVTDFFZDFuaFM0Cit3YWYxdGViL2U5N0RtMlM5VEVk
            cWxPVUpERGRHYWFueU9MaVVYb0RHRW8KLS0tIDlsUGIvcmVISEdRVGgrZkJ1VVdy
            dG1tOXBJOWh4Q3h3cjBYTU5BRXl1anMKJmgOYGx2/GbrNdIuFbuSY2hTQHyg4dcF
            nX1lEDESze8kx7LP0dtJ0dqj7ek6Sobvik+jAuLVL7boIuEUQt0loQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wcyzl9vjwakzxtxzw2qupn5332q7kpe8j4zyz434dcx2frqwd58qeutllz
    lastmodified: "2026-08-04T19:30:20Z"
    mac: ENC[AES256_GCM,data:9DjOCRzaNvkJZunrDLbGK3MsaOidSIPuJf9qG8dcbWBIzVvUleEBd/pmVcjZ/9IK1QYxjbaf1T1GK2Xc9yb5ZGX9Ipn3EnsOHqz2a0kJRDfqlqwPfdYn9LQ4QASMjFNAE6JBvmDW/WOSJlzSuofUoUdSI/qFVSi/68QM/v0Mbwo=,iv:5rukL9/n2MPLtjNVA3wXehL4dD9wuBJ6jx8n6jcyxZE=,tag:SaBCL654a2lyESvEks18uA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
