apiVersion: ENC[AES256_GCM,data:jrI=,iv:lCCqnS2UvNuWJPiu8+CMM1GkNP8bfhxSMkMRDveBBzU=,tag:BYf6byaS+3iZbI9nIOyJmA==,type:str]
kind: ENC[AES256_GCM,data:aFJZeWfT,iv:N4S0yI/PTD8Ij3db0E3/CKUedp+fU2ZdO1gHAocGMHY=,tag:B14B9MVIXHBXyQMTlEP1HA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:LNEmJ8J/7FKZe9x5JJM=,iv:gI95nqYwAZkFXXQobl6kxG/V51X2FHnmqVqLwMeHWjg=,tag:JyT7pkL87zurJCQQS1eiIg==,type:str]
    namespace: ENC[AES256_GCM,data:1aKcYFI=,iv:vNebTLJzQppFBhODJd6NSGnLPqzc0x21FqixxiM/gt8=,tag:xlBFJ3GU0nhLn8Ao1YWDIQ==,type:str]
type: ENC[AES256_GCM,data:TfPpmz5f,iv:P8X7nFOThG/Uvsy+4JrWsEkQ5pS5luVxEQ1qq4toArI=,tag:N4FeZUDH2Q7MEwWZ+lmwNg==,type:str]
stringData:
    #ENC[AES256_GCM,data:6286pcYQE+0UlwdcDguUQbVsFow+XY7zKEaONLRElM9nB99MR210MBTteiMMNw1HLDNsoH45pRsTHg56kQhIlNczmMoY5AeO5ICBojk79pg=,iv:SHBdT7PvOYsvmLW+xRTL0wxg2d3VcCUww31lOs83JBU=,tag:ZyqsEzIRvlwornfI/2yW8Q==,type:comment]
    #ENC[AES256_GCM,data:zqWR/CRTfsIaJtfinzy2jQ9mcmodY3tRIdocH0GC+OPMzlN07OJCA5EZKtqph+R0A42AMbB97U3lLA==,iv:Am/fe/PFdnvU+5UnYo1yahZ4eQSg6+AyxdGw401BDAE=,tag:IaQ1D7LGvEzC5/iC/HTp0w==,type:comment]
    USER: ENC[AES256_GCM,data:bQ2LDj1qN/A=,iv:lhuztoKucAlij9gY2nI7agkPjQ8p7EjJZvlFNf66n3c=,tag:5Pb2YvoD6hrBNo+TKNYTBg==,type:str]
    PASS: ENC[AES256_GCM,data:rGLIZTkOXEvWbwNYsnwDh7cQ6ZP10IZDiR/q6AKh,iv:qTy092rdLsu4Dsz4HOkKw762eTLPKs7T1OSbmF+/7dM=,tag:28A9QZXu/Zg2vTpdsHCH2A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGSy91Rklsa1JFaWpETjBx
            MXl1NU02NlgyMXpOQjZFamtVZGQ4bjUyS3lzCmNXZGxuRktzc1FkeW1OekxmVjlU
            VjM1aE1WRllnSGNIWTB3T3B6VU5YdWcKLS0tIDdIMFJzbDF1M1RxbTFSbEd4YlJq
            UkZLNHJFaFVZSUpBSWpQUExjR3dxencKw7eJp+J0ks/dz7IMzjOqd7pVlPooeLgJ
            M28PR7f0c85C+JttM5nBbjEsfDXnrmR25i8vXUx6qj1VmlcRPHvbdw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wcyzl9vjwakzxtxzw2qupn5332q7kpe8j4zyz434dcx2frqwd58qeutllz
    lastmodified: "2026-08-04T18:42:34Z"
    mac: ENC[AES256_GCM,data:/LXIVgaG/xLvFWphx+s0w1Ro3/zt9TMS7mOgnOZKhVu5bs/gXDjsCAVXEQarWheFiE2DtudcFglHPznl/ePx/WFttP7yvvqh4ZdYTzCYnRey1dGNucWsmXzKHzSQAW69viu3RBqXk236xhXZkq6v/GC0X8HDULbLSADkb1Dp2j4=,iv:pfXj34qjDO1TC84mkyu3Ni8GfjHn6A+bPeZmSVdshD4=,tag:QkkPBiV6A1I7a4WSVDTimQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
