apiVersion: ENC[AES256_GCM,data:kpQ=,iv:fXd1Wixo8qTXux85Ar4MGo7r4zafB10aTpin5QWClsg=,tag:UcES8Ousj2hNcAbhd2auUQ==,type:str]
kind: ENC[AES256_GCM,data:a40t4tYk,iv:gfhFZHnNkL6gZc5wkAELG3dl1BRpJipHJieGUAeO2rw=,tag:trKK1PuzZy1LCkU2AlKcPQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:rWRvUAP6hoEMbHoTVLC2Yw==,iv:RVpD1pIYcbtPrUmLP3MPST698wO3WexkCJD5oOZAFek=,tag:ylAXYuHBZyFgMOZo+J9yag==,type:str]
    namespace: ENC[AES256_GCM,data:89fp/WyNnLSg0g==,iv:ddVpbWvmJT5BBe+57+VGIKNkd94HLKSkO4Ona77ViWk=,tag:PpvP/gvQhSWhNysZIijAnw==,type:str]
type: ENC[AES256_GCM,data:x2TabXO8,iv:7ScxKnr6BODMqqFhmAxlZVfDls0bLXpxCbm7xN//wkg=,tag:7Wq4pqNgiB2A7O+5KXrKaA==,type:str]
stringData:
    #ENC[AES256_GCM,data:4bQtus9bOslGRGcu3dHlkDSbhT/vK3I98i6uYET79MHCiXcTsyGsSkkysDdmm5QM23wxn3afzcmdlbpeR/6delJKWtNc0EsCZ4cRiQ==,iv:dgf3X1JD8psKI9HygDQrEyDbuP4NApB3y0kBfkrslKM=,tag:0ZJV1FKw5SUhznNtksIqsA==,type:comment]
    #ENC[AES256_GCM,data:yBZN+BxZdae9k5DbBd3qzhCTZT8R1ozMCgOwQ3DON81XdQfUCqOP7z+kqM0Dh66VQouE1PSS933Cb1MEZFeve1tysB3Bvpg5NCw=,iv:25DC4xxNTLn+6VJPSqjMYRZC5/TRn1FNo9I0XSFbGh0=,tag:Q/CiLCqSrpNc1PvNnpXp2g==,type:comment]
    #ENC[AES256_GCM,data:tegTPLtMn0aPK5064/mKJBU0tiAs2x/KCSX5uE57XBTn7QtVyL8zjmuez7MlnGnLXf0ZgbVonbV/QVgkxw==,iv:ROVoum7PqRVs91AJ/c1EsQiWJwjjPZ/xltEeyvJTJ30=,tag:T0pUjXuJgBsrd5zZYAtmMg==,type:comment]
    #ENC[AES256_GCM,data:GgTNk3HEXZ2isBi9D+GF+W2fxlmRX/PSnL5brSclfxrr6/BNz+qWeiFoUOolQthgKKfTosklnYC4Jqcux5/3GaKjl6/0J2g=,iv:sTh/NY4/+TH8Bcze7jAHzxGqf2rGlUATb1uy3gjFDl4=,tag:EywMA2ilV7R47UO/p8iFng==,type:comment]
    #ENC[AES256_GCM,data:3EbrH6jAC5XpZEgOCtvKDwTf7HRWy4/uyxHLI4ynpvC47NfvqdaRqdtLImx634bBX6hsG1tQ7NYRr+L6dmgXQyPEw40e0jQwL2FZz6mKdnjs,iv:biQlRyzsZdCi5oIeBjU3ZTmT1IWaQx4aZh6yJqEc8Bk=,tag:XY/oXQ/rpkYEx2E6IcznEw==,type:comment]
    alertmanager-url: ENC[AES256_GCM,data:GwNPoW3SZPvopAJn4J7PN21F0fwOEF/Q2G/MWUkvCA3g4nngOBnvFO7oFH7Emw7jWkrg0Fi1hnFSKCZ9okZ/+iUValAOBYKP3Zd8hHelSe3GZqV7udfXBUiVIs8zPI7O9iK/klQbEy7Ah0J5taqFSW3aIFyW2AqpoA==,iv:p+dMRWjVPxZ+P2i5RvAahoEZ07oKc2Kh5o02TiGPbw8=,tag:51yR7bftNAw0/2tFwYyPIg==,type:str]
    grafana-url: ENC[AES256_GCM,data:vqZAWsAyoFLO9j8a+b89ID0gQfZFkhyjyIPrN28B3T/ExLgs58pET5hYpl2QWWTL/oJzUrOB1RpsFzFfR5l//hsVCJgH/hBTeUxhIRJS5D45zfGtJT7v+moNuf6vuWiKFGIRL5AD6GWhZ0IzFt4txa/uGBN50YvYRA==,iv:rCX44t/qOR1RsYWgIfNR88vfvMQ6PK9NIYBfAShqiBQ=,tag:ZwNStH1CgPwjOIqyOfApWg==,type:str]
sops:
    age:
        - recipient: age1wcyzl9vjwakzxtxzw2qupn5332q7kpe8j4zyz434dcx2frqwd58qeutllz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzVTFDNjRKdi9lYWtBVjIy
            ZFd2M1pmL0s4emFTSDhxWUZ3YWptb3hoNEFjCk5Za1F4OG5Sa1ptdW5JVGlhVHhu
            a0xxVDBTN2owQUd6SW1Hc1p5VGxoZHcKLS0tIHljTUhYV3BtTTYvQkFXMElKb3BP
            TWxZZytkL2pqQ1ViREYxQ3lXeUtQWlUKgQn7LHRWRfvJQMJ9IrMA8xmrOX1aV0/w
            0ztsuctDFU+rUQhLWL8A8sh3teStdwSpYPGod99wr/zZ8v34SMUMJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-10T21:50:04Z"
    mac: ENC[AES256_GCM,data:saUXsLmywUvlj2eWCxQDclKhbqhoe1csoCVVTyUSrQ7KXY5+Q2SOgE6OZ3JOuMvblkC7x3wAuH5OFts8wSiOknw6CeEv2aDaxVME8sc6QgAhPAPlJF1pE55zvBKZh45WmvkBZLBvG7QwwsBvUiaLZ7k2XM+A+rFaRFP6OuIdjCQ=,iv:anU2j+MxwmZ/PBjGJIaDOlpIHaTIQt6nHIf7ZoCE8DE=,tag:djqUhRD/xnbCMV22ef1HHQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
