apiVersion: ENC[AES256_GCM,data:6ww=,iv:b18LQXRRsyH0Va2cAj70Ts/e6KSKwC/pE8ajCZ74GZY=,tag:jjthR0i+zDRa6yPfaxdZ7A==,type:str]
kind: ENC[AES256_GCM,data:GPN53iQ1,iv:n5Ic9hnavGx53n0fpSSQn8e0himrO1eeQ1qWJzXHFPs=,tag:Ljm/3si+NpQz8o4KQMLbZw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:bXT0LRZFE1ixFFSBAKkJVK+Tzd0=,iv:QFTlTkHEIO7Auzk9tYyhKRSObVoO6qsC1z20IVKt17I=,tag:FfZkRTBbLx26zC+V6VNn8w==,type:str]
    namespace: ENC[AES256_GCM,data:4bGwVYw80Zykew==,iv:sCxiVmnHUcTBrawd4TfI3mAyoJVa1vXrBSqtn0WWElw=,tag:n2ocw6aA8n/QHNsFwc70ww==,type:str]
type: ENC[AES256_GCM,data:WPWbtFXP,iv:qGv7ZqKnJsaznI3Ym8g0lpIUKWmZJkTWgRiiGY5E6J8=,tag:1wsFuqeJgkx/pIojQ135Dg==,type:str]
stringData:
    client-secret: ENC[AES256_GCM,data:5+pBxS7vkCle0Mcv6eJ7/aCMft/nd8Z84gH8E6xNbSvIbGUX1n+Fu/tSWx3ZPrpefTz88A9qp2QF7BpNlk13+Q==,iv:0uVcNzy7+1QwKsJozfjZKNHFiH1N089NVNCDOh6vFz0=,tag:Jrg8llw65uckHD2Z1kVxGw==,type:str]
sops:
    age:
        - recipient: age1wcyzl9vjwakzxtxzw2qupn5332q7kpe8j4zyz434dcx2frqwd58qeutllz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMeXZ1R0wvRVpMMjJ3dkNl
            OEE5SGt1K2NqakxzcEJKK2NHT3JNbStXL2dvCnRHNTZ2SUw1Q3JRSWo4bU1Xa0t1
            d2Q4UWJrRWl4TVJFS051cVIvVnhzUHcKLS0tIFE4L01kTDNUQlc0Vy9aSDVGdTBT
            czc4RTh4VW1ycDlaWGpid2FhUU03RW8KeUt4Lb2XfH/vAthNDO98wHTwc40Rdlwl
            vrzIjD+1EaKWuzAAsxMRRvHI8HWA9gmPckdX2jlqAIo/yLGDBbZiow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-27T15:18:37Z"
    mac: ENC[AES256_GCM,data:4QonCmRWgGRAlo6LSYz5DjBw5I1TDUQ5tIS0ZvYhAxvt8azuRW3oE+V0UOMPWUEdUcBM1EYt5jrl6r4UnLA1kMajV1iV9OEqvO02X0P50nm7e9ymGzPRaM0939x+fDAxiHEldHXuh1tJErsv2ClOCqrBp3rQqHM3dapYzVja/XM=,iv:i7oKX5Y+orfOG/VDWEhlsjdFnidUaWKt+UiRMZ7Hkng=,tag:KVHe/rgD+bT5KNBRDCD5lQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
