---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrepository-thanos-community.yaml
  - grafana-admin.sops.yaml
  - grafana-oauth-secret.sops.yaml
  - thanos-objstore.sops.yaml
  - grafana-ingress.yaml
  - kube-prometheus-stack/helmrelease.yaml
  - thanos/helmrelease.yaml
