---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - bentopdf/helmrelease.yaml
  - bentopdf/ingress.yaml
  - it-tools/helmrelease.yaml
  - it-tools/ingress.yaml
