apiVersion: ENC[AES256_GCM,data:/4A=,iv:Te4+Ma/P12UnRjyzitXLwQMMOKcxwJi7GfmdtF+0nho=,tag:YwxAXfMU8cYK/d9IMuZ32A==,type:str]
kind: ENC[AES256_GCM,data:cOzdHiMg,iv:5Uci4zEO9iE4A+rE1YWmaIlt/+y05JZNHB/r2Lw7Hcw=,tag:iX/DjRS1OnIAqQnEgFXzXg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:X+j7fURZXypaGSTqxcjODNtrNfk=,iv:33xzCqreL1DvAkVsfdLhT7HEu8gJchX1hSQSIaNbX/A=,tag:pbhVRJASYbuGkrKORAgVUw==,type:str]
    namespace: ENC[AES256_GCM,data:j9sHGlCwR5eGqeQmdg==,iv:1LdOx7CBHNC60/z9Na1zfqv94yxKRK10MWuIEbrPZ6I=,tag:fLpaAqR6EaIXgRCTT7ULbw==,type:str]
type: ENC[AES256_GCM,data:kvzaML5S,iv:C3eV2J5lTnMq4KqspNLpvrXYFbSdVVU2D6plJulPVsI=,tag:VXVwceulbUKkQuFdtIeMaA==,type:str]
stringData:
    DISCORD_TOKEN: ENC[AES256_GCM,data:BtwL+7LBhMEIOO9s3O7n9otUCpxpSdF+yg2P35m5iEH3AuqXoUvs1dlWv5w6gW0gFZcmLQjmczNvNB//t2OB3gvXWRj/MAtD,iv:Phgf1zZIGua1et3y7vyB1tI0osqrJHZL3a66Ry8sP7E=,tag:559EwHU4SFbicANU1DvNFQ==,type:str]
    GUILD_ID: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMaFZQMGhnbENIbSt6dnpq
            VTR5ZEJMODZ5eTRUN1BUdmxQbytXUnJXanpRCkpkVmI4alV5bGZWV25UTjJOaFM4
            dTdYNFpnaDR0VWlmdFlNZHRva2kyL3MKLS0tIDArZks5eEcwQmRzaDNqNlhpeUEx
            Wm5LVlNaN0tBSXBaZ0MxaVNQVEdRSjAKAybmlHkB3us5+kFPPRL5RL9TdDPAMOS1
            J6rcMVaK7rJ/fDawaxhupo6pbrqQPfTe7ZLW4M22APfnH2oE4PRebw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wcyzl9vjwakzxtxzw2qupn5332q7kpe8j4zyz434dcx2frqwd58qeutllz
    lastmodified: "2026-08-12T00:45:34Z"
    mac: ENC[AES256_GCM,data:qZQwF9dI1NNdnDT9NftL5jwzMULmXTSLzol9wky6eeSXXo6/vlhxQXvdMYgb995emgU3QncL1nMbRtjQu3lz44JPoMcKBCFd7iUiZPW10Z9ytvQQiumCNshIPYvuBMDY6AjbS+qUrwhU7RrUJsWL/JkmoeOilETRdXbYTjIjEVc=,iv:9BlKgFcT/zdGpNQOULM0LmLacOhiUPs8KksYzLhuoks=,tag:dCwn6yy9HVHipv8ZqDMrlw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
