apiVersion: ENC[AES256_GCM,data:/4A=,iv:Te4+Ma/P12UnRjyzitXLwQMMOKcxwJi7GfmdtF+0nho=,tag:YwxAXfMU8cYK/d9IMuZ32A==,type:str]
kind: ENC[AES256_GCM,data:cOzdHiMg,iv:5Uci4zEO9iE4A+rE1YWmaIlt/+y05JZNHB/r2Lw7Hcw=,tag:iX/DjRS1OnIAqQnEgFXzXg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:X+j7fURZXypaGSTqxcjODNtrNfk=,iv:33xzCqreL1DvAkVsfdLhT7HEu8gJchX1hSQSIaNbX/A=,tag:pbhVRJASYbuGkrKORAgVUw==,type:str]
    namespace: ENC[AES256_GCM,data:j9sHGlCwR5eGqeQmdg==,iv:1LdOx7CBHNC60/z9Na1zfqv94yxKRK10MWuIEbrPZ6I=,tag:fLpaAqR6EaIXgRCTT7ULbw==,type:str]
type: ENC[AES256_GCM,data:kvzaML5S,iv:C3eV2J5lTnMq4KqspNLpvrXYFbSdVVU2D6plJulPVsI=,tag:VXVwceulbUKkQuFdtIeMaA==,type:str]
stringData:
    DISCORD_TOKEN: ENC[AES256_GCM,data:MTKhdZgvXcmpmRyxw7jteOYSt06q13jsd3LSiX3F,iv:GMyd3i/OkMA5YWVSmVioijrQJjM4KifG/BRIiUvtbms=,tag:GbvYI9UeCZd3qNW4Zkk7FQ==,type:str]
    GUILD_ID: ENC[AES256_GCM,data:nyFcRiSfDgFsVnqm9Nid7YjI3vbXvWswUxQ2mGs=,iv:DloZoqr3W2YgN2yW1HHVAoW+x8m+jC84+yYf7kLbNq4=,tag:cdWNGDEhKFTX/9icGEAxTQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMaFZQMGhnbENIbSt6dnpq
            VTR5ZEJMODZ5eTRUN1BUdmxQbytXUnJXanpRCkpkVmI4alV5bGZWV25UTjJOaFM4
            dTdYNFpnaDR0VWlmdFlNZHRva2kyL3MKLS0tIDArZks5eEcwQmRzaDNqNlhpeUEx
            Wm5LVlNaN0tBSXBaZ0MxaVNQVEdRSjAKAybmlHkB3us5+kFPPRL5RL9TdDPAMOS1
            J6rcMVaK7rJ/fDawaxhupo6pbrqQPfTe7ZLW4M22APfnH2oE4PRebw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wcyzl9vjwakzxtxzw2qupn5332q7kpe8j4zyz434dcx2frqwd58qeutllz
    lastmodified: "2026-08-12T00:19:58Z"
    mac: ENC[AES256_GCM,data:6dHtb/ihwSf6FDCuS+ncmaYzo5KXDbFZX/xbu8ayVl9uW6Ehegto3AJ4rZUUt0rodgKMRJywuuWEDrkFA4oKvpRP4O1FlznUZVItm4HBxJWt2Y3YcKNiX2DdfBuFKR3I/HIAA5YPyM/n9A+xxlcOEKJhEKfIZwYPIEN3Cf9rraw=,iv:mN2xTR1oOuAXHxB7thfkZIU9H2FHYY2MVZB1CSDNFlE=,tag:zlcWRZPlrx1GoZPieZKC+g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
