apiVersion: ENC[AES256_GCM,data:tKc=,iv:e1JsdTRVzVrDPjr0HynjSBzCe9orHdlgGYAcHwiqOPs=,tag:ChTNIvbCB7+EJ/WCQDvcuA==,type:str]
kind: ENC[AES256_GCM,data:SaKDzzrM,iv:DPqJ1tT7DMl09pbszWfImxW9ut8i1tCFulXMzgYKAY0=,tag:V18TMbLA0I3byzkODM/k4w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:NfgDkAzUObOELlwjMQKLtrQi/A==,iv:ndzbBVt/MaAFH99xlBRzXvifhfT2ZVjdazWav2HIYog=,tag:t5IJXaLeZMHgh+TJ+aujsA==,type:str]
    namespace: ENC[AES256_GCM,data:I79VHTmH9zj62w==,iv:ffLxX6znEM1gPCeBLWsgFSqsa9jGq4GG7M1/uWiypoA=,tag:E3C5MWJTUD+033dQbqP5sw==,type:str]
type: ENC[AES256_GCM,data:Z33sx5ub,iv:bJLiLUNKrqO+MjEJOg4ZzMEZBpJxlfCo6QgX3h1Qmkk=,tag:TXgKXffgHBA3SnACatxzRA==,type:str]
stringData:
    #ENC[AES256_GCM,data:Zehnp//TLIHbr3CxsPymUfvzunm1XsZgN6jQZJwVJJvGRhDRJegrGYZfbcrFkpFTITNm9jxFnOKA7K63H1jIVwy0/sZVy1Rtdw==,iv:i55qE2R5bO9RlrvmDdnO7DFJGy436ahoiYDaI8fyrL4=,tag:YVq6oUB7ou7CGNxhEjEoqg==,type:comment]
    #ENC[AES256_GCM,data:VsISAIUGfRedMeOZefjjK0iVzIIJsCaiUuLjIiybGNM=,iv:HXbK0Y0CDEYXolIJ6HtLWEBwsXcnjv2qplf+yguDDf8=,tag:8P1TqyD/9RjQZJB+0kOIHg==,type:comment]
    #ENC[AES256_GCM,data:n4UkQpCih5Z8nctu/cmAKiatLEg510xXyJxeKudX6Bt/EWv0Gsbv09XzDRn+SYosvvhi+Ar7TA==,iv:igPgSKFo8t0Lhriak9rU5k94Lybt++ydtXC2z0Dc738=,tag:vTyRLP3eGVJELUBgoGbruQ==,type:comment]
    #ENC[AES256_GCM,data:A5POEBCNEq+GyeldJFrHhjd5yIWgYcvj4ZbvfC7JUlDO7lt6UR4hyxmcEwKSHyT11vMk087aR8t/gmEEKg==,iv:LrXvW+F9zg524QwWWn76eMgc0X8KG6LZ6FnoXOu2RT4=,tag:M9RAe6ejVRxIjreVF0Ettg==,type:comment]
    #ENC[AES256_GCM,data:a+RPUBwAexhCl8yXG2jb07efWSFcyU42DlqHT48hJekDPZjhgBZsq52sB7glgnWQE1W0Xab2CUfQjXJ2/3bF,iv:XbTrYS0pvTOZcvc/HhgyOKRXzxYVEatedtItOSuYLK0=,tag:dgB9SwC6/LMwc1bQoNyJWw==,type:comment]
    #ENC[AES256_GCM,data:78gEQNd7Fw9J1vnuqqh/AMISbW/Su45Xx+gpFlj4/x5aPIXQHzWcvGn/IeT25D33AWoJTIUF+1VR5uWOq0H/Sf0=,iv:1PaXi8W1KXv8lDYGNYrpZAXA3okARtKhyW9hao3sJnI=,tag:0DSV1CRyCYh+3Qx1WoIyVA==,type:comment]
    #ENC[AES256_GCM,data:FzdeSu2bGznIdx+CbCxYFB39M2i+lCA8IrqZbXgX1vnePAxV6m/hCWeJkw4X/yrRT1Uc9G/SIasK9zh3OA81MQ==,iv:l/uvMTY6aKz1RiOsBouBDdH7tWdnxleP4/tfN1jGcCY=,tag:IhwljQUHhvpI0V7w5M2hAQ==,type:comment]
    PVE_USER: ENC[AES256_GCM,data:qWhHgetFLjz+jXUX2B0=,iv:KWHZjH8H2imaaMY4le7R+ge5FlZnxqLEl5rKuDj1Pvk=,tag:NKOoo2UFvR1BJSKSDSqL6A==,type:str]
    PVE_TOKEN_NAME: ENC[AES256_GCM,data:RNRd0akUMyi+Qg==,iv:SW1ZRoQllAugdLOdaa7t7sjik3a3REFynmrkhX/hZg0=,tag:rg1pDs/gpiJ3dF7fA6zLEw==,type:str]
    PVE_TOKEN_VALUE: ENC[AES256_GCM,data:fIQ/bdHF9Px8ZH5Y9CUmwFBC9WgozOPtqvox3sO9pdMBdCa6,iv:yITMaHaf+IZwmfIwkjnhmrFB1uCy485sXDEYQPqJpfw=,tag:New3h72XLIlBSioHa7PdIw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtOGJBWVVTd3ppQUNGclRz
            UkdtemdhM0owd1ljcE1vb1l6VmtJeDFYcFZjCmVRQzI5M2xacmtYVjlmUWwrdU53
            c3RjZUNPWEl4alU0ZHdOSjNjSXloR28KLS0tIGRXUWdVMGZ0d2ZidGF1QmliR2Qz
            OHgrOE5WYjdhTGxBRnU1cWZMVW4wU0UKRQu2+xYzpgJ0ZSfNVogw0NqBOh3VrCwX
            MzVkF5hP/x1kXaEvM+HTmw8hPJf/Poaa/1N/aroQ8ooEWK7Ij1ZFTA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wcyzl9vjwakzxtxzw2qupn5332q7kpe8j4zyz434dcx2frqwd58qeutllz
    lastmodified: "2026-08-06T17:28:08Z"
    mac: ENC[AES256_GCM,data:p6nE3K1TtuxkTVXdchAGj88A78okQqM0vI3aO9rkMuT6Rl6xxJ3pxI4PyDyJUwqe3COJROUc3jYExbc8wUdrH1L8Hgc4xc5bs792ZcXgYryvcB4c/qr0DuW4JkHq/5bOg9PJCNDnS6rtEU4NI7cilWeVvEWKlR3omt+relXvOH0=,iv:zP9n6H8hnRUkcvwRHJShe8JEd6ZUkFd70RwFa0aG7W4=,tag:aYUwryIH17aDZgluOkg3bA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
