apiVersion: ENC[AES256_GCM,data:KjI=,iv:G+IR5nrxvrP1eh3G5Q4vXQDFLThbPwAH2wzSrTCXiC8=,tag:YS88p3E4F3TkQPfc9dDrMw==,type:str]
kind: ENC[AES256_GCM,data:fnVu9NMF,iv:6Rf3U4lNxK8AHYFsv470XTipT/LAawqB1uLwncGMNIE=,tag:bUhdnzjLjHYTRYHJCT8VRA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:7psSneyzx9SRVPI9Lhqts9A=,iv:m3lEP8nqgjLmj5xRVQAShnnX+m7sluOh5qFQZHuOm4I=,tag:PTc/wSgpGReZ5f4qN8JG1A==,type:str]
    namespace: ENC[AES256_GCM,data:opI4ebMJhygNhw==,iv:PQdOYtaRkUypGFpywSrdYzYFsmUS/yYHmPxEmmAtVIE=,tag:83NewWkDX1+h0lJFkN34tA==,type:str]
type: ENC[AES256_GCM,data:EIVHW5Gh,iv:qx6IM8imz/GoBWJr/Nman/En0fDO16Dc+gDVd/Y+IKg=,tag:Bze0zTVRlrENa0yZsy9ACA==,type:str]
stringData:
    DNS_SERVER_ADMIN_PASSWORD: ENC[AES256_GCM,data:YvIeHRWjpn9SkBNtjLlH1nGsALd6vHsuzVlNOg==,iv:GoK7bUYvJHdM37mo81oYHC5ubY7fIzmR+brm2xMZ/r0=,tag:6lvYgbuGg4Y16BQxn71uWQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SG9QRUw4ZG82MlUvaDJu
            OW1KYzBuZFQ2MS9UdlRja2c3MWhaRDlVUVNJCjIyWk15cXBjUitpejFKWHdYTytU
            MDByaVRJc29ESnFFYjY0L3gvMWFaaGMKLS0tIFlwVGRrQ1BZTXVKSk9MU2tIdWor
            TW11WGhCT1MrYWdZN3FyRytCUkVOZlEKrhNMu+aE4Xkwy6JO7Z4EIs2CZFWUaj1D
            rvjse/zlC2PDC23TA47TvY0xPP5kDrVmqUGJkmAaoeRwaYIpoTw1GQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wcyzl9vjwakzxtxzw2qupn5332q7kpe8j4zyz434dcx2frqwd58qeutllz
    lastmodified: "2026-08-11T20:15:03Z"
    mac: ENC[AES256_GCM,data:fAoGYZ2o8h7Y7gXwt6n78+Ex4F/3mWUa+3tZKoHXxbCREZlRwwqn1osm4lKMA4slgenC0gxTYsoq4ENkPLX9szqI9qMXYcFwJ9YBtRHTgytMLshii07TQSv5zvgZ60queE1SUVtkWKmjryB+5RJ/+O5gJsr3dv3o1o8ZFqlnNkk=,iv:e+S1mrpoig+zwMWLovTGxOGlEo91+z/VUxbdCnR0d9o=,tag:yP4/3alaUBfNxPi+Jms0cQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
