apiVersion: ENC[AES256_GCM,data:0mI=,iv:TRXENBQz1fIuF+jRpEZ0cRlStVKQfRKGvbYybBwj91A=,tag:0T1ULONcIKj0Y7UubLV/nA==,type:str]
kind: ENC[AES256_GCM,data:t/RQKHRm,iv:pDM9LxTRbIC1jatcbYOFUBnkHcU8A59i5RQQ12AEYHw=,tag:D4OBrrYIMWiP8TQ3BLhzTw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:9Bb7YbWqoCzAOsjUNai963U3RMIhaVzW,iv:KdjkfAklaAFuc3V+5HVzDsf2oiIdkf63ERe6gw7atgc=,tag:+FpS0zbeK36eVpYwGLe8ew==,type:str]
    namespace: ENC[AES256_GCM,data:IbrCgJaLZr7y+Q==,iv:OtbK0F3qQB3Pj/flNqzCrk2SLAqM1TbEv7CN9gLc7lY=,tag:IZ4Sv5lSp+bMa8VMW7UaWw==,type:str]
type: ENC[AES256_GCM,data:f0Mv/wMW,iv:9vR/+2PvZRdEX8GjhNLDGIactp6CHF1UHLAphS76w7Q=,tag:ATdpWmlVQgmNPcv6Fe6dEg==,type:str]
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:t9RohaIeZWGVwk1r46gM/R9sMjgI8PGdNW6A9A==,iv:tWZSz9xJqoMeP2Gj18yG5Iw7bX76J1vILu8m0EPJD5E=,tag:zGKI9T7JLjGvoklZFpOw5A==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:bOky+0Zz76upVJU306XQf6Y38g8hmKNVZqGRux960hc1KpMLhe6ykvI98uLeXTnJ2dKX6mhxuqw=,iv:hNGhKvPguVtTZOk+3DRi/bg4WFLEhAG8A0saaPZjfTA=,tag:AHqvDMnF3jJ0G3IccLPz3g==,type:str]
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:XUG0B7rLqJWeC2L9JOzmhezCoNv28KUFop1s2D2qgOQGD3yr+Lldd9D6N/mb,iv:dY+u94tE34pTllSswJeJsySkoc9Nwx7skERHSr//8KY=,tag:3LHa6EHrJp5eSsYImOB7Yg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:PmaIogc9sf/Sp5tT6H4re/cAm07iFdyfAtVvopQ8TiR4mbPFajxBTZufSKW+Hd8f,iv:WT3u5Fat95RNC5M8+GHNRTs5zufmvYXacLvY3fBG/Dw=,tag:MVBf8keVp16O9lbjWEaAcg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVUc5aVc2RmVvT1dWSHQ0
            VmNQdS9DSnd5bXVoWnVMTkJVSkpEWmxpYzBJCmsrWlRZM1NKeUZkd25aUmZtcW5x
            cjFib2phUE5mYzNnM2RZUHNZTlFmYTgKLS0tIEhlYmRKSkp5ZTdnNTdQeGpEdFgr
            MGo5SUluVWxWUUh4N3QzY1JxZUNabXcKF9Ii0XugJ/N0RHOlYQhd7EQcWALJ9yW2
            NNYmFvilJdde1Ks3bwSZs4JmKRdpkFj7sEzdkSc/D8Z6jJ36zjC9fQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wcyzl9vjwakzxtxzw2qupn5332q7kpe8j4zyz434dcx2frqwd58qeutllz
    lastmodified: "2026-08-11T20:15:03Z"
    mac: ENC[AES256_GCM,data:2WsF+nNWYgvYD0FbFyk9l77UyB0os6YJ/ASE4ILsZFQaaGcHm44dOI1CTlczK/dY4EIVZ+Jo5XEDWW+J4uViCcHbL2hN9VvL/A2BdBcNEonlG/SRZPdu1jZ7qw2UaBWal29X00qZ49jkpA2UO23NU7ejeqmWMExKcYvSP3TGmfE=,iv:tmN5CABSJ8IuYYJopxlpXya3WJB7L7L/ibHFrABN9Vg=,tag:LqMywH8ktU3GJmY9WgpaSA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
