apiVersion: ENC[AES256_GCM,data:4e8=,iv:TI5V74i4oVijMmnxsU+5wbY4FaRl3he00LrY7Jao7kM=,tag:LD0PdQdzDuF1kdOB/FTXLw==,type:str]
kind: ENC[AES256_GCM,data:j8tDpmc4,iv:EfdLFl2yO36xDaJkhdcbRRXop5MgWHFHo9GGy0CQAyE=,tag:SJ9NHRPW2/rERLtYSp/33g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:n7BydF0e26XU1PYJwvudPTq/i9SfJk/dwjFN8g==,iv:P/MtTUNEBVr63D1Kl2mo45UKMpUBfFAj2iA+a65HohM=,tag:kRYqXt8uGojtZh0s9DphNQ==,type:str]
    namespace: ENC[AES256_GCM,data:JeEeG06DSMKVcjEgmFg=,iv:l3gQJWOorVgadoo6Ca5fHmX1YUAj4pF4uC5JKz69osA=,tag:+6rORd/XgIkZ9F9Yx/tITA==,type:str]
type: ENC[AES256_GCM,data:yBqJZNh1,iv:q0EreUQy9/WDqFCEXSCzlRd+eiETa059Vh9ZMa3H9KA=,tag:eQ/ZhotfBtH8ECVFZBtDsg==,type:str]
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:7kXn8cWmMb/+Oe4CAU3CkzDzVnWtROpl6vcyJA==,iv:ZJVt+05jy5RsUEQaWhuLULhPieKMl7rZla/j5XpfPn4=,tag:dCLgyvBossFiRkuw/ha63w==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:tWU+3sM7UopK3M/Bba7YDf33aXKgnaEBbBO3h1cXLhSySeD3y/rcdqNJnT3Yrvt2asPXAc9uVfw=,iv:Wv/iuALAc968bq1wMd3DIjOJJVveYtrSxPG976kL3UQ=,tag:h1qocpeZ3IlGGoTSBUcUow==,type:str]
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:0MB4zUR0AkI0Bv5nXW2vEOrbtIlsKNPlR4viBmadMa4a+/GRS816noCU11pPHAQ7Dg==,iv:YxgiQPR04JnMewy3lzZmtmoXQTh2wsP48YaUmgFTS1g=,tag:BZKNZKsGWImWeOcEUXJHTw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:/h2eJM4HAe8Naip+TYDRCACQiVzQhiHfwnzMn+VxfrBIQjNy14BYt0fa3kc=,iv:dp6CC4g70SVDszlAkgP9r4X/GXCnpil01Nzi3ukE99g=,tag:W1DhfLs3hHUAPEvGtLfRxg==,type:str]
sops:
    age:
        - recipient: age1wcyzl9vjwakzxtxzw2qupn5332q7kpe8j4zyz434dcx2frqwd58qeutllz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dFJoV0dQU3JXaFB6cWk2
            Wkg3K3pHWDg3SThLVmRTZWdoV2FWU1RxdWxnClV2c0hUNnRlVGVINVdIc0ljQjV4
            WHZCc2hDZ1YvUHlFN01jRWJ3MldpVjgKLS0tIFVJZm85bTR4eHhGMThYVkU1UjR1
            dWQyNm5LZXFhWk5LZnFnaDlsTVMrcFUKcODy4alU4VF0oKtY6k6HHimPNXsM5pC5
            alPAiMHtSZtbJxVwcKtESm7M2Nfc9BZ2DVAgHDg9LDq121RFATMG3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-02T03:00:55Z"
    mac: ENC[AES256_GCM,data:Vx8ou54o1TLpl73DKnyPJF0zhHbt9qFH5g+vF/XELeTiSJUpkumu9GfN7hIf9Q/+zwDQDZwJGyp5g+3Hg93Ga+cHSDBE4p+tzSr3jZRD3i2HBwVXctG6rqAX4zF7CqhLZkJh/HQnpHf2knK1lirRc8IVjsF6WXjih3p8fNatA4M=,iv:PS//La3bPpVoGHLO3lLkX9iMdKChf1Cj48kAXJNCTMA=,tag:9SqhDKdR+852JWy5R0DhBA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
