---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-library
  namespace: audiobookshelf
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: audiobookshelf-library
  resources:
    requests:
      storage: 5Ti
