apiVersion: ENC[AES256_GCM,data:k9s=,iv:h3WXtfUaETLUp6kjf78UVeItUz//ULAGzSkdWe4YtUI=,tag:4OekyWqofytW3WDZfsSGEA==,type:str]
kind: ENC[AES256_GCM,data:XXOqyNUO,iv:aMdBFOdg57sRmKMfu0BUdL0OxyYSPwj5HwhBrJxgfyI=,tag:+MXAMkHEDARfMPr6cRQQ2Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:510QfSwhILvRWJwNYR/x/UxSl60i0Tjq,iv:L9Wl/GsSL9U2og0UHx33LbjJaMEBgq/g12gyxIJyvpY=,tag:W4hWA0KvChwyP58Up9wdAQ==,type:str]
    namespace: ENC[AES256_GCM,data:y4lZrBI=,iv:RlKtfm83C5WT/H8/8lC6wKIVNAedani4cGRbAGyTvYs=,tag:SRJo94gvsZyNUrbqwExE/g==,type:str]
type: ENC[AES256_GCM,data:pOQ5aHxh,iv:IMCrKNxmMlJ9fcK1dQe4omlKT7kxe6EmMOUXiEC3EKM=,tag:C9QZycTaZMTNhHgEeYmLfw==,type:str]
stringData:
    API_KEY: ENC[AES256_GCM,data:vwcXvcjkKw5fcUbyekXqgpC16T4T2YXZo8y4nmjpiBw=,iv:zzuMaBDR/AQxjmofc77aOA7hfsmPjdLYayPxXZ86i/0=,tag:37Y7tueQ23ISZ+x9Gehapw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWlZhUEFxNUxkNkRhUjdx
            RDNzeDFQMUQyZG0zTTl5ZUdMK3hHZ0xaTjNzCjFFYXZmUHJ2a3p3cjFPdUVtNHox
            d2hlYk1SNWNiMzc4b1o1SGwzK3gxVHcKLS0tIFNGa3FKTy94NVg1VVZQc244YlpZ
            YXpYRG5XT2Y4VFRZOEZMMER2OHRMVlEKonopfyUFoGxJCv3UXkbbaBXPLa1cxZqT
            cfvgwrsIvZqGBGo+mBZEf9Vjd6tkG7H7OAo4lD10KHaQCw5VxKNKTw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wcyzl9vjwakzxtxzw2qupn5332q7kpe8j4zyz434dcx2frqwd58qeutllz
    lastmodified: "2026-08-04T19:30:20Z"
    mac: ENC[AES256_GCM,data:iWKfM0tnL7T/4s12g1rR2EQH2gQu/2zG55Ykjx6RdfYkMGU/W2D00FzhlubzyNyyjiSCdOxQbzPatEyRNlGMg9mdoalsLJJO6Q575Oz0hIrQ2NQDzVbqQMgfudrT0XLD7mfsp8fxGdLfwQ/fAaPhhrbKQ3AW1wH1Ym9vZLdfAcQ=,iv:CqW6PgTochbmQiLdia3Fk5LYOZ74xTzYxQzOGvQcO5s=,tag:neL4UsrhY025grsJk0SFlw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
