---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - controllers/cert-manager
  - controllers/traefik
  - controllers/snapshot-controller
  - controllers/volsync
  - controllers/cloudnative-pg
  - controllers/cnpg-barman-plugin
  - configs
