---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - controllers/cert-manager
  - controllers/traefik
  - controllers/crowdsec
  - controllers/snapshot-controller
  - controllers/longhorn
  - controllers/volsync
  - controllers/cloudnative-pg
  - controllers/cnpg-barman-plugin
  - controllers/mariadb-operator
  - controllers/system-upgrade-controller
  - controllers/tailscale-operator
  - controllers/external-dns
  - configs
