apiVersion: ENC[AES256_GCM,data:DSQ=,iv:HhIa1+b5L7/shgbHQMwn8qtBfhKZiGeBRnoTTsRVe8k=,tag:gO1OkY7a0qs79vWw7+Csvw==,type:str]
kind: ENC[AES256_GCM,data:U1JrobZF,iv:+nvCNuUDL51Z0EUXcv1m7K1cd7qRAdfcN9/vAvhNlKU=,tag:QON3wwDxKl9qadHsk/m8gQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:G/uP/sdjRrpUa9BZ1DgjM9hJDWbnsQ==,iv:frttDVXDi+uG+Wj4MVeWZDrNwv5EKfrJvF+cmJPCCqI=,tag:UwB68wlCRjQyhB0x1zwPFg==,type:str]
    namespace: ENC[AES256_GCM,data:IzDoqcI=,iv:Y/ooeCWqkBdumE70a+0IYr13YijSUho1k/jM3+TdFpg=,tag:wtH7gCw9JMId/V+Z9ao0kg==,type:str]
type: ENC[AES256_GCM,data:zhuAlL/O,iv:eTnKcXYYlZXYj84onPYec4ErnPHIBFaKe+mHkLeXj38=,tag:2ENtN53ECsMmXVGjC1Vrlg==,type:str]
stringData:
    API_KEY: ENC[AES256_GCM,data:iYeoPYAKPJsT1RgDrX6wn3MGpkuO1AkM9VPizNGaM5Y=,iv:/Ue0h8nZIFdqDCaS6rrcbpurxNwi8PCAk/HOsOWScUI=,tag:qVpMl+UTRJ3nGr98+ItMJQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dkdUbmlqZ2ZpSTJpd2Zi
            M2cyWWVZK2NIWlhXSDBsdG95QmhoRnBRWVZrCnB4STVMVzZJalNjeHBWZ2FxRkZX
            ZUN0c3prOWtta00zUUlIOVZ5U1hXV2cKLS0tIERsenpEZHFQeUtibVhpWmMxdU96
            QXRPTmNRNWkvZzlTYVRvQ1U3SEZveUkKA19iqt+B/bKopp/mSEUJAGKSV6KzAmoX
            kalMQgF2yklnSHdylczW23e/Tl0NIFCDOMzUMoVLf1G9Vuz+kAx24A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wcyzl9vjwakzxtxzw2qupn5332q7kpe8j4zyz434dcx2frqwd58qeutllz
    lastmodified: "2026-08-04T19:30:20Z"
    mac: ENC[AES256_GCM,data:wh33Nnt4hp4YnRPE1N3Xf9NpucSkKUVIfKOYvokfFwBEh6Wa+ZCKvOjoxAmj5d5cfekt4+hllegHfNix5nG5T7F7dmdwtTYAIGbq7l2o4Ot748NOCJBCiNqhwMq1RIwJ+yqaD8fvF9EJH1QqeVueYblyFcuJbhAB2Hy6xAblVjM=,iv:UpD5abaMnxf+BIoUfhrsZDithtTHFwWcDL68qV/unpc=,tag:AUheIE3RmIY4VSVr6HDg+A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
