apiVersion: ENC[AES256_GCM,data:DA8=,iv:AyLrQwen+ZTiPJgsso+TyD8Z/uuNGNM+p/5rvisgWwU=,tag:JNLFT6PsUgivuuRloDzLcw==,type:str]
kind: ENC[AES256_GCM,data:iVZlnVKQ,iv:lcH3iEqHCMwRxY8DKNl6NABUotsNh8yWQlAIGlBBnjw=,tag:w+mcVeEYbQApbjEltMDubQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Rk+NUBaJKVZZXjZvN3e9HB3UDaPfux4=,iv:wsMUuHegvK+glwp2pUBtQvK1bmU3KQddpL545LF/AgI=,tag:QBBI6SqMUazuNnRzS4oZrw==,type:str]
    namespace: ENC[AES256_GCM,data:ZCM/SGpZUDFtcw==,iv:n8BYDBpkwWe5R6Xl0JNKv/lOBEC7dLqeVf+Cl3mxDd0=,tag:IK6qwLBa/bpDgRW9CyPztw==,type:str]
type: ENC[AES256_GCM,data:A/Vu5mwk,iv:jLeoF4WV5yAXMrhx1dcotQlOjiP1NO76JiuB04g+64I=,tag:gt1hFyiWKeQpK3qPLV8MyA==,type:str]
stringData:
    sonarr: ENC[AES256_GCM,data:MQQyX9ZvNoBWLHcnWEYnfXYvS7s59dprBCOR71ke5VBfIGgVbiLIy1d8UZYm/hKjG8g/q4Q9N6uRqm1STzPnLELju6cYfhuxJG0izmr19LIrpHiRJIa4JNgXLDCvHC4=,iv:VnMAet/uYUAZv69Q3UgdqBcjNLZa5HIXRyjqI6pnPq8=,tag:ZgTDU+VlfXI4Qn5X/RhVqg==,type:str]
    radarr: ENC[AES256_GCM,data:fhIK2WC8VIzhgbtp6/IIdyxD4cZ2ywYE8J7+SMGAAhD5vzmj5dzHjk5gyOBxF3HbkvdhYlsqTMGpMPDqq9n01Qkz4PNw3qpzND8+3OSXBb2QRNaMWCg033K+u113QEU=,iv:dI8r8LfsiYnSepWFAXTB8etrfJfcw4fq1fXJFB23Ttk=,tag:1qsifjsm/qKGBbNUG9xidQ==,type:str]
    prowlarr: ENC[AES256_GCM,data:cXm5pjwpE2hn8RYawzqejJazBYBB5K9lHdrVl2CJjLl3U/2bHI0WlOQ5KZcQUcGWYzGkM56Nb5S91KizshUFaMMhcjCCTlGj7140sVna5CPVCkFonv1zLdUw0WVrmr8=,iv:rn8EAmvVNZ6YQW1mWL4uTW3t2aODg2rduhFk6EQytX4=,tag:GZV54XDN9rJyC/b236TvGg==,type:str]
    seerr: ENC[AES256_GCM,data:zBCG2Az6ly+3PkQxQn4VlEI6er46uXDzABzNSkbRoOMNISz7agexk/gWKQq4WSyy7+JMMt/yay2YgZwM6Z0km0x6AGep/xUeHhyBOlxqeCdQE/1v99PwKpN6pMeRGW8=,iv:x+duqFqETtLmbMrtmATK+Bm5rrDFtdcrzZydkx5BFuo=,tag:XSF2jbJtxa98gB4iXxLO0w==,type:str]
    tracearr: ENC[AES256_GCM,data:N1lAbCVQ9gfTQvbZkkXj9ch1n9+ZOgdnYKWIQGH2QRsDwtgsiJECDE5D/09P6JgvYGrrZ69lBG7gZpHnoXYpNtyIVHGVPu8d3X1FgNG1DAgay18d5eM8hzRJSUnwMQI=,iv:19Krqozx1UHz2rKOwnh8CGepbes5N5WnY9plL3Jh5qU=,tag:DGPSxtb4s9umEl4a1kVxCQ==,type:str]
    uptime-kuma: ENC[AES256_GCM,data:/4LqZQQrc+nPusNY5AcRD2ejtNJiX6sPwpIZ6uMR8gcFWwYKIadClfuBuYySf/E1eS9bpihEOxdMvU8rkaI4eNi08IsTFqEBpFZVuOHFpU3bdCGZLoEq8P0BTx+vdOg=,iv:9vOitCBGYqWPSM/9KImmmEMCLkSUXE/UNW6HWp/OPN8=,tag:DLHWSu0aj+GRomET9T/20g==,type:str]
    etcd: ENC[AES256_GCM,data:EUJzybfqhiVFEDsZMnwdBk+alGz5sgrFevyL6cJwPZh+UB5ttmBUqNclRCL9EKjyO4RT93QXh9nsd69PR9tBuK/eCc3Cuv9LFeeO/AWT29BLanGOggtinqPwXtSD+kU=,iv:jOJXX8bLBTPH9/4HrgZD++mjXwVmjwS/ZPfyZ3KQB1M=,tag:34Y48jiCfWXPEMXLjqdfrw==,type:str]
sops:
    age:
        - recipient: age1wcyzl9vjwakzxtxzw2qupn5332q7kpe8j4zyz434dcx2frqwd58qeutllz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3VUdXaHhpbnhvMm5XV2F2
            QW5rZVVBSXBDVEtHT1VJRkw5TDNhRHU4U2lRCmhacklNa0xtMWdMNlYxTEJrNVRR
            OXNqR3ZOc0tySk1PYVc5VG91Nmp1b0kKLS0tIGIzcVZQYnRVa1IxS3RCODhkQnky
            cWtQdnBodVNpeXphZWpseWY4ZDhud28KOd1dsPes2Vwt9c7PqihXUneTrMR7azBb
            NoEn+2kBrds9lc0MVG7/HgXDfcKNs8Zbx7VLCoxsDGCCS5NytH2vyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-25T00:45:33Z"
    mac: ENC[AES256_GCM,data:xsYZeiy6waT1DotnMoy7YGVz5tYdPlhPemfLApo+VEUkghYY5C5a/G+ryfCgruwz4CjFh3iwyVCzQCqAFf6qEreve8qay7/DHYVWxfGqzwjwTRR6Ojx8JGBvshGDa+7VsY7Qcmr3Lpq+UCjwBGy0JsKlBDxD62XI5l2/aKJVgTc=,iv:FwsmtLj4h71pP2KsiNDDXgv+3OWPxKlCJ8T4v13ECr4=,tag:PnJHxEn5nQoa4OMpziBT4g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
