apiVersion: ENC[AES256_GCM,data:kf8=,iv:LU44D3bvD+pSdAkxFaseTXzlv0qkUxHGx41TX6e5nPg=,tag:iS+E3HqipyUcM8pxgeDfuw==,type:str]
kind: ENC[AES256_GCM,data:s2KCRUMb,iv:OttA76T52DiZaZAjAJ215Ch+IMSsZq8x6tqmNkar8eE=,tag:9HD8cnF4ccNJiD/i/yVZng==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Cl4bP2UKqrft7KGn6FaBg0T2Hdfh9OY=,iv:uTFZCFM8Hdm5oaiG1675+TDGO1bEZG3ZvF7JMJPR2V8=,tag:JmRku5YN4CvrVFKTZdwK0w==,type:str]
    namespace: ENC[AES256_GCM,data:PWJuysKroF02Iw==,iv:/tTRdIdmcSKMxlPeEa8dYSbdn1ujxxoQkHeTluNY9HA=,tag:DEbkAfCadphBFjHyieYjxg==,type:str]
type: ENC[AES256_GCM,data:YgRqU8ik,iv:tkLok3XuoniR2R2uvWEvgkDt6OgE9dYXXeAhR3t26Pc=,tag:0GKenlfjdR4KR5r+BSEYdw==,type:str]
stringData:
    #ENC[AES256_GCM,data:yzFh99/265XAaYaaumpCAB1a2xdDalVwPQvpRwosmseq0fb2XNeuSE4nYkDx1+xfxSCVTMyE/SboH1ne0jmY847NxmSm/WY+R52UZg==,iv:FtrnWHnrI/YT2P6kE2eMRh+btrgqBoaMLhm2iuIynAg=,tag:KTr0R2ZoV+aWxbb2uqk85g==,type:comment]
    #ENC[AES256_GCM,data:1MHjysR56We1/ZPcNkwWVSCIHtejBU4/uXgbZabuwKskuizwWjHsX1xI6jcNOEXO7xcypAaGIjR7fQvvjIzOauoutd0wUy8P2JVDqefdlaWPBbdHIptDf9RYQpQo,iv:Q/uzTkkU6sUhD/iQwgOYjIPgVdJ6hjU9zA9x7h442LU=,tag:SVwJuGhq4D2Gf5h00xe8XQ==,type:comment]
    sonarr: ENC[AES256_GCM,data:LS/rUiT7DOu1VaQepN0V7tGPMMJvZHE=,iv:Xfan0opK3MUmbZDNXG2w8QyBwizem0hQ5Lcslt9THAY=,tag:wcgTz/sFmwivlq13OB+xzw==,type:str]
    radarr: ENC[AES256_GCM,data:ihYs86Kk+DycmzZnANIugJpemEdsquE=,iv:P5KzG9b9DrFktZXb/g/Bxi1nUaLqnVziBNU/Oz1QFv4=,tag:m9J1x/Q2cnED9BIfqMjoGA==,type:str]
    prowlarr: ENC[AES256_GCM,data:4+n8FhyrohHsufxtC9zRwHs3+btyClc=,iv:vIlohbfJV2ZCoMQBc0+vbt0q30GnqEDKEbrm7CJpi+4=,tag:4czIz0Gj3YdKaItIRNN0nQ==,type:str]
    seerr: ENC[AES256_GCM,data:gSPTlDZiB4BtfT/UuI3NukKwWzMjiAQ=,iv:a0POS+NM8JFwcr+QutJ0ESVncF3AZuIUDCeX271Hi3I=,tag:2kMOyRLSsjdTY+I2cOrMXw==,type:str]
    tracearr: ENC[AES256_GCM,data:qE8hHvOyzZXx+EKCujx3+Mjd8F8Rko0=,iv:8WpIik0Tn0OG4JmlBvP9RtddBqtHFm4KAM1GVF/Dk50=,tag:xkPVs9pSrj3tiwg+GqRzLA==,type:str]
    uptime-kuma: ENC[AES256_GCM,data:K6ozmaAWLLLXo8L85QGY1s0WlRsQKDY=,iv:tfnZ08fjuBksOZbLiEtK6bRho+C3q/8jHCxYUfT9ZiU=,tag:DeKshtZZH2y3qbQToRL1lg==,type:str]
    etcd: ENC[AES256_GCM,data:CGh8deuYiYjOfPrey0QdEKvyB/06y30=,iv:+oaxh4RlBz6/BGWpAJR1A7MYBXE6Onm9aPOHpmvPES0=,tag:srfZnTpP1J16EJNqotpgVw==,type:str]
sops:
    age:
        - recipient: age1wcyzl9vjwakzxtxzw2qupn5332q7kpe8j4zyz434dcx2frqwd58qeutllz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVVhrbDJ1OEJUN1VLSnh0
            T0Y3N3VPS1BreXZTdnBDaVBsejZkT3FTM1RRCkNxNXVqOUU0eEhVK3RYV0ZlZDEz
            MFdJSWErNjd4UjNxemNqT2VZQ1F0MjQKLS0tIFNpZU84SE1aakdRZ2hERE9XMkNx
            cy9SOGQzdWhadWhRclhTQjdFamRoS2cKFL51NcciJNeJ9VESCJU0LaETtlaBFddp
            E1Q3aHFR+t/x8ynU1+V838fu5Iz54oCHO3g3QqvzqRF2FXfsYZGWfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-25T00:22:30Z"
    mac: ENC[AES256_GCM,data:1JuTLmLd4lCefVM9Dhm6g9zJEO6BjW3S2ERcLiHyMjBT5XElhlVLfUifbvoO9JEEuiXJbNQjZhxc4GR5/oYV7dMdoZco61aj9CIAxnZFbfrbHXJ5dWxa4wz/Eq+dPBFtrys/Fh1mm57TykQCmFKTp/DeGJfPryf1i061JJyIyP4=,iv:LDouQwBtzhNR8tSJqqwnYTwd8/dC+hSLIdQErZc4H+s=,tag:uRe9oBkzOsZvmx4T3YLcIw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
