apiVersion: ENC[AES256_GCM,data:Qr0=,iv:FqLacsFg1CmSDFlVLQNjVIRpB4Eq47pjPl2Dy14u5DA=,tag:Y9tw4HVqb4Hxo6tN09t5pA==,type:str]
kind: ENC[AES256_GCM,data:CLdBvcU7,iv:XVryb5YpdZWLP+JW6a16YwW096pa0y4Ef1+TgWAY7u0=,tag:HTBuFik7yMCY7+1jb/u0cA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:wYmOi3cBx8ZErD0w4O9dxq8PTRQGlg==,iv:0+y/49BTAdXf4yTgXEPXgEcTbPmnPCmza7kzStCRADM=,tag:we6H3hATYHbumRkhbsy76g==,type:str]
    namespace: ENC[AES256_GCM,data:GkGiiHZuiLvKAQ==,iv:pRtYsKDGKR5FlJMIOaxu6LhlmFCnd5iR43VqevHouPM=,tag:wwr18loY7qIuj3ph959uIg==,type:str]
type: ENC[AES256_GCM,data:XI7aLf9v,iv:I52iku8ogU9tICpGu01iSoC4o12bLLZU3/0r8Lj0EVk=,tag:iPi+CzMT2DA0NEc8rCNvuQ==,type:str]
stringData:
    #ENC[AES256_GCM,data:n84yWPd+7LTJTAvEaHYKb/ExVETQnemkeoJb92l94XKb6Np/nL/CiA3mOwgBWR5zBw+lhh4sCYy3YdUIXTh16REzVV9TziyHtMt19A7rWQ==,iv:H+W9n8Ri6q8coZIPWjJVN/2mPNWxgzGTVkwfcXNHpRo=,tag:0176ZbozQYvw0jYhk1JXXA==,type:comment]
    #ENC[AES256_GCM,data:VDned2Tp8Ac7rF4heQ==,iv:wpxoXokLyFH44VpjNz6mgnXXc8BMMInNrXNUylOkfgI=,tag:nJCjrk5ILONA5QEMtj0hqA==,type:comment]
    #
    #ENC[AES256_GCM,data:psPX89GAjvnUEdwOz2A78T46T/pke0UBhJjjVuVRiYDt+5Babt4wdklfwExILb1uIiL1X9Q6yBkhDFaoX4LkziOnzhI=,iv:ck0PtElPTjSrnNz4At5mfsgdM6IpK3EG9sz0/LKGE/8=,tag:1uU2wgpXt7oH5WxOXuo5Mg==,type:comment]
    #ENC[AES256_GCM,data:bT3sibu3iHshpRy1Mqe9sZVLui4L2sYCe9B2Va2690UMansKIyX34Gdd1vPtnu/5l8Z+qq3emcfebdTFH387RzyrYxVu5PWqGuQ=,iv:87I7fRrBBpM84e/YzrFcoy3DpytP2DFkXG2Vg/R/5ho=,tag:xOsxemxORKCH1Pg+dj4LEg==,type:comment]
    #ENC[AES256_GCM,data:mPnJ6678H1EC+SZUfw5af3dQ9Ty+GtgPecQMb5GXjzEix/bWAAXH/s+ylYVm7pBf9rnNiBRJ3T8uAAR/Df/A4sSJnwlJj9+Deaqf1+4=,iv:RbRBDUh3bkMA27wlWmjO3m7VIBKvyhtZmpP4xAJXt/s=,tag:+Ss45CI/V7dWpjm8OQ1mhQ==,type:comment]
    #ENC[AES256_GCM,data:p7iaNc4FvPj/s1hJKbjLiPmJZQKCmN4H+/o87ym0L2iatilq1+toYAdCmYQ1zCqhwPBi7QudKw==,iv:9mibmYviOhbZhvPUEsUiCq9g+OLwuGujzq8jGHYe6ko=,tag:bftCX2L14EwiRMZmpQQMDQ==,type:comment]
    HYDROS_PROVIDER_KEY: ENC[AES256_GCM,data:iHrjc3d+mp492A==,iv:mkhk8RrvWPwhJIZP6Nix46xcYjGcrFk01qig4WI4Z3E=,tag:TRRpmYutENuTRcQj2Q0JFA==,type:str]
    HYDROS_DEVICE_KEY: ENC[AES256_GCM,data:jInjjwXsa4YbMQ==,iv:xOrCO4Q8+7TRYy7ONOAtzqDH9Ji7G9mv3/Bryfoi7Po=,tag:FZb4U5GPpeHfrDLL6WbNsg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1VVpNazVSajJUNVVJTS92
            SlZFTkNPcEM3eHlaNHVsaUExNHptS0kwRHdjCk9wMTltV3VNelFKY2tFOSsrMDdD
            RlRnTXU0UFZHMkRVMWw3UDBvOVQ5RTAKLS0tIDNSazFNcTNtazNBaUNiZW1oVDlo
            aEo2b2FNcnA1dEpSaWh1VWNpVEUzamMKJRxDjqQYYLXzoy98uDFIzCP2POHpy16L
            blKh54OvMheuzPWPwj2tX6/ahHv1DDaPbYXrRJ5M6oT8OFxm9PVEXg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wcyzl9vjwakzxtxzw2qupn5332q7kpe8j4zyz434dcx2frqwd58qeutllz
    lastmodified: "2026-08-24T23:22:06Z"
    mac: ENC[AES256_GCM,data:nVzrEjyXB8St2DXTtn95t3sLglUCjPlmJies/OXrYcdwG09Tl0uSb894ov+GFLf3QjaEPiniYv4+M+pwh/4vcn04l15KSqw1i1prMJSzLXTGy3AAZbinZP5/r0MTDtrzFehTfQh6LQaZ9W13RaiN3s/RlMrQzYvJp7+xnhR4aEI=,iv:H85/Idl9TINYLiWqtXJBqkniCfhJiQDgHZqARzkTFPA=,tag:IOJuc5YpQl1/sG8kpaq1Gg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
