apiVersion: ENC[AES256_GCM,data:q6s=,iv:UALSh4XCmGSpGBnkHAtioeAzFIyRkCSQUVsJyzCfBYA=,tag:x0eBaImvFNjWd0vzU5obpQ==,type:str]
kind: ENC[AES256_GCM,data:y4H0HU3p,iv:zBBAaPy61Oo4oM3tptVQ7+WDbZStxQLXAt9xaK1YzIA=,tag:6PCncK46fs0GRkQ7n4HDHA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:h82lSNS32rjvuP27ZHJEwQ==,iv:rpznyet4TajnUXas31Hqfk+ipuzzVSwfVytuPYOIwiU=,tag:qXgAaC2D46g/eiy17KnUAQ==,type:str]
    namespace: ENC[AES256_GCM,data:ua5il3IC8Dmw,iv:emsixczLONff7+c6+8TizYAdlU585BoFEY2SmgYpbGI=,tag:cASPJW6ui9jaFbzwLZ/mRQ==,type:str]
type: ENC[AES256_GCM,data:ITbnYFzJ,iv:IAqmqWk5YWZh/4nMfHVoIzadMlE1aqwJ802q1xQqWds=,tag:2vZ2u8sxvcfb/JbZqKCYAQ==,type:str]
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:L88gjWk+8Y6zitgYuDOBhoil97JsnOFHQ7cz7YEfs8DlrJxeQJPrKrd9k86pAt4Ez76j0iyJHpJf289/gRZHp2akW1sEKOugLDVsbSFo9aVFMHcRHIkYDA==,iv:i08SCqbNVlidb2bOMxZRu9ViHB9FksEP7PWnlXeohR0=,tag:u6o6Qt84JF++HjAiIG5PTQ==,type:str]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:FNa2SOA=,iv:Dy7+QpDV9oElvyP+W9Xb9EGtyl6hTGwhi8n5TZM0Vmk=,tag:vAv4+HxqyAy4cZxxHrBLAg==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:R50bukejbcfZ9UfXdqrzuufqksd6fpjvjxTncKWYc4A=,iv:RzSIQOZjVw3Ic6GURQqRicpOow3joMlmjChVY/ONwwU=,tag:IK5PsCg3bHlPBOYfTRphBQ==,type:str]
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:VKX8n9btCBlcsViRLb+5hNlQ37lbtTw8WhH9Lw24Kp+RpOXIp+pCEQkifRNxaMIrZXlDveN4LGOqNNPzwb5b5S6A630D/2KBkCbVheshTFVyxx33YZzruX8jwoSsLuqm0RziiitjvTYFGjxh4WkAGBrnEoRAxHhwSjsWXSsbwpea3yi/d/V70rLyOJOQ7vNXNAIBdOIjltN20mzgbBGKtDYSVS9sYneHrLL9tDYiclEkwb3HiHTTRCBBrsBTuO//O0+UszQO5sUDfGSQW9e2moH9NO4Cjux19WAhzaov8WK8UnrhUnu9C+QdrXBD9zaWxsgaiOBeLHHAFypXTiShNItFDS9zxTdQyZtGUfeGCnF1Ig9JypM3DIR1fnyEtoGXQUHf7WYOYw==,iv:eI2u7/lVQdsUvaciI+45qgKtnyhau38KZIWANmAXuvY=,tag:BdUl6tfHtFpR7Z75DsoUCQ==,type:str]
sops:
    age:
        - recipient: age1wcyzl9vjwakzxtxzw2qupn5332q7kpe8j4zyz434dcx2frqwd58qeutllz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvcVJIQVBuQ3o0ZlE4aE50
            RGNHSUFxZkxxSXM5VG1Zdzc5VjZvNjh6eVdRClR2dmR2UmNPeW96QWRtR2ZuQk54
            K2RKbDMzZXA1czNoRGk2Z3puSndrT1UKLS0tIEhEWTZhbWNQbWQ2Tmo2VmV4L1dF
            VVlpcGxZcUFjVzNkVFFPcW50dzQ5RU0K0d3xSApEkBqUjtwlghosw6oBU13MA+bA
            igOix969AxmXxCeY2hUtA+ULriT8oOzTuk8UNosgExMPU4rg5zFFuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-28T12:23:09Z"
    mac: ENC[AES256_GCM,data:zr3bTNEn6VAf4PqA08eJkSWwc2CgDbFGvWwI/C4XO0D5Y/Zwc5k8Ief0Uu+TGom52Vo823Ysa5/jKCI8yvSZs/6yI0jhcUBXK6DJQ3Y02grRnRzCDcjdIUIs4gzq6SFeL+ESeVg6rFn/29LVaJf1MtjGSuqJeREOGXhoYoGo2HY=,iv:HqZ4G5OZrUMQRrpy+1zxHGWC1Xs/fn95hfRKXs9KpNg=,tag:PDZrcXIiRQC2HaF2JuhgqA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
