apiVersion: ENC[AES256_GCM,data:eKg=,iv:hJlnv3KINlRRvLC3fvFNmgkMu7sKW4lOlSj2xdSkcD4=,tag:S5FvaZouV8eDyqXPfQT1og==,type:str]
kind: ENC[AES256_GCM,data:MFmg+fzg,iv:Udoas/BVqA7Xde+ee4THFrFRIy51i/UqVn8XKiEJEKY=,tag:XQHTdREvhtGp8nQw1I+Bmg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:vUCXvp3inS0p4I3z9hLX,iv:mDQTeqYGpH1HHSagIPEVOhAhdALRy28kW7CB/tAP934=,tag:ZSFBKWwIzJgsMv4md+kJDw==,type:str]
    namespace: ENC[AES256_GCM,data:gQJpTYOkhmioLNE=,iv:gjPfCWXfq6r6mPQJuqOtyi75qXHBH+4kCpB2EhQq+Ac=,tag:beV8KJ9MH/ODDj/7Aoqtvw==,type:str]
type: ENC[AES256_GCM,data:e4vFlxI1,iv:SDldhjpJRfAElwSwzVQrvlXiaHjjhoFBmHn0g8V0ulI=,tag:sJXpOffnrtWTxpQVP9utyw==,type:str]
stringData:
    #ENC[AES256_GCM,data:oXGFVzXAzBlWOkNLcUpk/aABKZGy8TH0O/8ZGoJtGF+Sdkyu/rqa/z9kMdQK4LI7a3lzWbLHDpeyi3o91aKD62c8MhKZvJWYWjQutcQ=,iv:3tJjd5PvlANdp//Es71W3SiICsngwwAm6F5jEc9rmpw=,tag:JnkkK7rKa5YRulK50FW5Xw==,type:comment]
    #ENC[AES256_GCM,data:dO6e+G+4NGF4PcACJ9+D9/u4/m5mE2L6e04VbKaKUh8RBsO1bY5vH1smFkI5NHDo8dIhF7i4sQN5fac1GTnN6VCPeP4iKg==,iv:aEnKlLSOS/i4aYxSh8aJw5goPVWgpjW+zZHjYjk4ivg=,tag:odgvbSNJ1IjwVKXDNprWIA==,type:comment]
    #ENC[AES256_GCM,data:QtF5MDr9sA7xY5UhqTsGrdBqSJlZ94W3Gc65/o/pCOkMl1j/S+gbchvVHxZggA==,iv:cRpJemqqTdiMxo9Q754DzE05GnJ3nj+qBv+p068LF4o=,tag:0KXm46isQkY7/VUBSY5rJw==,type:comment]
    #ENC[AES256_GCM,data:oxkHgccos25Rk3XuTtsRfj6GnBIyc3ks3LFdVDaJX5Y2+YxaEWQa+a3nXPhNPs24PBrG1N04MJyF0iNOia7/5wY1PF1X1aet,iv:PJyYwqxIF5Pib/BEmK5+C1CxCaAOJzwUWhw2Cdij2hk=,tag:+k2v1sUtGeilIXPdI3WJYw==,type:comment]
    address: ENC[AES256_GCM,data:pZmjkKbBsft39czmLNe+tSkLJ3pCuXUlff+QaujKN+dRoQpDsMsYv1D4EXOjMqzBrQ5qwjVVLi+azpAMnF1CHF/qjSZ9gzXobP8IXi7RuobFZIWgBHFsoon4AtDqhNu0IF3xqrfbLSbRbkmdqsng5m7e40BnYoXMfQ==,iv:+hGGs0O7OaJBnyQwN2zHxQhweD/KUzLFJ+Jirl1ca+M=,tag:KPR23wvlLex1zHzrKphStg==,type:str]
sops:
    age:
        - recipient: age1wcyzl9vjwakzxtxzw2qupn5332q7kpe8j4zyz434dcx2frqwd58qeutllz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJOHZBQndUZGx2d2pkcWJX
            aGUwa1pYaGNoOGF2eVNoN3Z3R1ZPWjl0alh3CnlWWjYvTWJpUUVrWkU5amZuRmt5
            Yzl5eGNqYmpNRTRTMHpLbi9HcjFGQm8KLS0tIG5URDFMZlNQQzZqcUkrUnlmUlkr
            UkVta29tcWJjWUpSMkFGZFRCa3M2MHcKu+5tjo3tKTVMIHTpZH18+aeao+5z3AyN
            gqUOeXyGaQMEADfVmCn7NX8fZBgt0TxH6lOLL9qk9Ya0t8e4bVO3GQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-10T21:51:02Z"
    mac: ENC[AES256_GCM,data:TSwaGnANnzQI3vhH545asJjpQIcVKwtm4jOnrHXmJqMUCb0Uox+gdzngykMknpX6MU59FIaCTYavfktohukcWNfX16HwdBmj0lVk6c5XRywjO3YIz7JcSNMmMhLH8kLkWtS8H3ApKfcSY/8a/0dSFkencWWQtqW1cwzycZepDD8=,iv:zs5yTrIC36Xya1A1JxexrXUIlmgMd61w6PEvoS1rnZo=,tag:0zTnJP5KBaBY3pNo7Qhr/A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
