apiVersion: ENC[AES256_GCM,data:/AI=,iv:UtqNQH0Ar7g8Z77ObIFsax4wva1DFEiW1UODLGisYgc=,tag:kuzulWO65Wtv0okzVhRp0A==,type:str]
kind: ENC[AES256_GCM,data:+qkBgFYC,iv:vgb3xCkWfg3AA4pai66GIhLsQ00RXVL+/TFmBnVsNM8=,tag:vPd4rQR7/Fncg+sksIm5wg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:IUxjcc1HIvvdzzN/eoHQaWQMZC6jeA==,iv:EKxnWvaEAnx6ZkHCkiqT2CUkQyNd0vfBHCLjyd6Szg0=,tag:XlIB0lW54Pll+w8N9K5uuQ==,type:str]
    namespace: ENC[AES256_GCM,data:e3SbIa4=,iv:AO+xrj6AzkdP7juZuiTggEym32FC2xKASLFAsIo+cyw=,tag:0uNulbqWUx1MLv0XCWOx5Q==,type:str]
type: ENC[AES256_GCM,data:9xpxpyXW,iv:MEpOamjukS5BqC7XnsI/xrkLziGe1FWhf7qiHilw4fg=,tag:+OqELEbqtVtD6f7uc5/4+Q==,type:str]
stringData:
    API_KEY: ENC[AES256_GCM,data:lD09+hFp4dzBtxUZRItCkkxJbEF5dA6BazaRIPxd5+8=,iv:uxrzNHKwI8EK/nDztdWHK8VX+R7kSSiwDzm/E66P+kg=,tag:0oEAIKRqxkznQuBbDypyQw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1R0dsSzVSNUlRUGVjRTZy
            U1BlWi9HVUVoOUdvbFFidmdYRDRudlF6bVhRCmVwWnBPbHY1QUNRWml4ak9lbzJo
            OUxiaHU3d21ScnRHcGg0UmhsV1lsVjQKLS0tIHhKcVYvaU02Qkx6a1FPVlBOMFVq
            bDVhS1dtR2VyQXo3bGcvc1k5RG5aV1UK4+ZiOnDR3E8NCQtuvo7hI+HWYh4IcbtC
            KN/1c4lvbfoWD8spXUKMCsbmC93kTyXpzsNydNt3Zd8IbkeX+LKlwg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wcyzl9vjwakzxtxzw2qupn5332q7kpe8j4zyz434dcx2frqwd58qeutllz
    lastmodified: "2026-08-04T19:30:20Z"
    mac: ENC[AES256_GCM,data:d/yrmFlpu7fCX/NywSqqJAtlnNMDon46yZL+iSgpurrXXVn0vssoaymKcbVNYVMkQKDMUi+OjZmy2QRSAjqaAC+g0ZFm8ML/HFQ5lC/0o5MvzQQ4+T06Rm9lXziVAjEgFROn+68+9mQ4TWTDBWF8OPw57THBqMR2SybNv1wGIrg=,iv:1TBYq9GkgyiudEJ8zMEWLir7VH0qcbDeCLY2opAAuqc=,tag:G/5Wsez5O3zlotEU70/rmw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
