apiVersion: ENC[AES256_GCM,data:UD0=,iv:kHmvpT7AfJuJj1q5nwUob0itWfeDaAReT0uODUnbqaM=,tag:TljKCutD4LpZv7CfGmz5+Q==,type:str]
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:pVkudR3RuzFmV5qIhlo5e/h1mlN4lS0sRynoUw==,iv:zaLE1T0ibulgdQBoC/X3uX7pqKTJGvFrJyusxcru9iU=,tag:Rzr9s+IyjHw4PeeZOQZtWw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:9LcBIZGB4G1mTuO7HVa0OLOjksl4PKIagLkzEFuxJ38N0sVLQUIG34/ix9ka87UmgVjmee2+yCw=,iv:jesjTZRLeVEJzeitbc5jW9siLGArUnv1UvGdOLVmj9E=,tag:Axds9osGAt3d2p+J0qLUCA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:mJs0Npb6UrNut5z/XD+bURu4ShTvvarlE1fUh2xve31RCXtxqECedpfLHjcAChqmLtwONMLKvjxevC0T,iv:FSF8Ntu55Qn/t8Q5JJFNNnOWx77e1/PSNK6w94ujRZ0=,tag:tT0cSfcig+x8PPg9nEf29A==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:8HcJs5dsQdXBt/mpMZbap+ht94LauUyH2zU9Pe0T3ZfALGpTTXP85YzFHog1qN5eVzylVQ==,iv:EkLT1vlcI2hzCVxfFwcHz5929aLqDXEpHVqDmQu5RGk=,tag:ZitOPGmyvuGIh1zelObryQ==,type:str]
kind: ENC[AES256_GCM,data:Rq4V3soU,iv:zAhf84nGRLnO+aachZNYTzXFRYhpx4PJgFrZhpVXu18=,tag:woH0BfzGrckY20m4UBa+/Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:7H14t1Iu9e6bQynPZs45PMw=,iv:HEDOyHuI/GyKhYkQDlFa0IFe/6pvLh2H/qIO5e6svQw=,tag:YEzjP6hHa1sPzFZAbLxjig==,type:str]
    namespace: ENC[AES256_GCM,data:tOQO,iv:ScPmmeMmMOG6EJGtjNGohqNBNuboNAOC36taoSPhToQ=,tag:OKTW3BGQaM7aeBdrMaFP6A==,type:str]
sops:
    age:
        - recipient: age1wcyzl9vjwakzxtxzw2qupn5332q7kpe8j4zyz434dcx2frqwd58qeutllz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpM2NUM0JMUzhYaVlURzJS
            MkwrdCsvbHVyUkxkbm1nOWNLRml5NCtGSEJVCkwzWFNMZW5qT25Ja1I5ajFhTWQw
            TldtbUtGalFEc2lKcEp4QWx3R25FRm8KLS0tIHk3TjJ2M20wa1RPWXp6QzQrRHdh
            Nk9WTE5VeHkwdk96N0I3aFZuZTFkcGsK8P+Rr6DsL55biS8I+s820Bo5PmoSFOfs
            saMf46foMPKcvEi/i0SA3Z9CEkSUunbk4vFS3S5BOP2ScVnRmJB0Gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-28T00:37:30Z"
    mac: ENC[AES256_GCM,data:AKSqGfK47kDsyIZNWRtaQbeuE4cvS1zmLnPvb7FsA+VCSwk2RPqWk5MZ5jEz4k9cEvCCN20I3hw5o7eE6xtL7X+eLNf3vlB+UzAAlAqp1AnMtM9ClBYPqyBgiOuoHRKtKjBt5/osnZr2Y4/fGBmF2SPh5teHdPd8il91ZXlx8Gc=,iv:Ud9lDEpCVXoB7GCR7yPwXu3Rcf9bAr0kvMMiPrR5n0M=,tag:VegcccT3X6fG0lGxIVKOxg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
