apiVersion: ENC[AES256_GCM,data:pSs=,iv:R/F6XMW+S85C7dTw9pq8bzrGknH3/7TYpEPc7DggsrQ=,tag:nEkRVG2JK8m0fkRv9FIMJg==,type:str]
data:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:MhQuS5ST4FWX3uA3xQX6Tw16muqtCImpoU4upr7WpumWPOor+vFQf3IOGN/asZKg5zABsRdqMnaCeBnH+zkHkB/zKu84lOWYYzZGC/iETqP11VleQyPVoQ==,iv:drDl4/JPPvb/vrxyGlaihGG6pmCqj1NE5I2OCInZpZ0=,tag:94MtsWgD+v2HqX4oACmxLw==,type:str]
kind: ENC[AES256_GCM,data:GBlljp67,iv:efHjKVoNMvHr/S1wUz/YT4D71KohS4GUSgrjUBMNx6Q=,tag:M2adbh3trrhHe8kLnnE8nQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:LeiwIXN+WXsjFg==,iv:zmCm35ymtnFj5OAjdX4X2DV9YB8lULiFXFduuyFti9s=,tag:+04A2NDQemGT9RWQMvKemA==,type:str]
    namespace: ENC[AES256_GCM,data:GuJz,iv:CiLdmZCvpJeTEV2YdI4O1oJKLQyLhB/u8xFLlobdkv8=,tag:Q/KrrGub71HV8smoqrNmNQ==,type:str]
sops:
    age:
        - recipient: age1wcyzl9vjwakzxtxzw2qupn5332q7kpe8j4zyz434dcx2frqwd58qeutllz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0MFl5U1h0UzYzM25aY0Nn
            UzRlbDJzanNZMlIyajRlZTlQTDRXLy9MYWxFCktSSkxrWTVZTWRYdWRmWUNhbW4x
            STdWeGU2NG5JOTRLNUQ0VFpMSm52Zm8KLS0tIE5keitGdnpjK2VGeEZZUUFKUXo4
            QmdyQlJCQmlOOGhYTC9VK2Fsb3JQeWcKOdID6je/amsWeb6RCqZfi+vr0loh8wAt
            VIiuaMPIiv99DnhcIwW60ZalHemslht4l5geJpSlfVnltoftzvS/xw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-28T00:37:30Z"
    mac: ENC[AES256_GCM,data:lJJSeKax8s+AtZpCLSaIwTHCLzBWaGf3tDo1EUQJv/0j7587fA2XMbsEjUrtMRnoveuWCb2x8Kh5NGjWpL/Ovr2m9ZxwdamRpBs8vrOu8jDtUHSg1doqCV8SUgeAz4DRYMxS+uGfG3rhXKEKwBmU2ph7uIbYJjfPBnkhvE5VaOI=,iv:vyOGiVQW0QRtOdH7jvU/QqgccUFuo3ZVWOGfcMpLHPo=,tag:OnTSxuWtS4nVqnCliu3wiQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
