apiVersion: ENC[AES256_GCM,data:N8I=,iv:Fr5rhexAhA/MMWPhXt8H8isqrsDGTv3rL42z9ZgjXts=,tag:X6Exy5Pi3AwQza0zUeqQcg==,type:str]
kind: ENC[AES256_GCM,data:86gNuDwu,iv:47iTBrS6hLHuTcQJpCSkJtqrSagkcm+uIgfVWBLKhps=,tag:w0Zat8sXGe1y5rT+MGLGaw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:WRPpu4q07xaCQh+fhdDYF7DtelH/L2Y=,iv:bb2OntvRhBgnWZAxKsGuV4j2nk36LPV1hZ8Gs9bBWc8=,tag:UkwXXqewGFmtKaUJb1uzCw==,type:str]
    namespace: ENC[AES256_GCM,data:GS2POvT1+bY=,iv:QF78EFymXEy3vnYl3Uiq0DE/AJOKTjvVYtobnJZ1v0I=,tag:ykBSwOiTciaJBGrk4I03TA==,type:str]
type: ENC[AES256_GCM,data:1d5Cmsq0,iv:4xi1GZekfNkYJmzsQpqOKM0c3Er6R1AWLDEvXyNS4HU=,tag:iBpzWaa7/PlNWjsEKcUE2w==,type:str]
stringData:
    #ENC[AES256_GCM,data:cKSK90SxEzgL7mfEykDACYDC9Hd9bnfcTIxvaiRuUNEubc+uMP2GbnOxFMuyTkE+2uWc28BH5mZRRccML2PzeincNOdm9w8DjWSjZlXq1f8=,iv:oBz3UF+9NBIfuV0NbrfnG0yzU+tjD6o/oaj2o2Yj3Uo=,tag:fUB9Zo/w6++EbHGBh51+OA==,type:comment]
    ENROLL_KEY: ENC[AES256_GCM,data:r09FFMua3FgyLjGS7eYdYGDn8dNWQlAD2g==,iv:l1zhuaa/OvIp7oRbfy7Z1+XvMD9gbNTe0n83CaeKXls=,tag:QJO5meqdLlhbvRnjfzBF4g==,type:str]
sops:
    age:
        - recipient: age1wcyzl9vjwakzxtxzw2qupn5332q7kpe8j4zyz434dcx2frqwd58qeutllz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTFZiYnVHSDJPUGFaMlR4
            dWlaWnVMZk1tR3N1Z1hBNmJxVjJqYmRiYXdVClBUSW5LQXlvaytvSGk0dTdSRVlH
            aktUbE1DWnRrVWlXb2VRTHdXd0hhL1EKLS0tIGk2OWorSTh2TTB4bUxxUXB5c2I3
            dDlUNFJBelhUcVpsdHFTWEFLUlZ0Q28KHL2GMIhpBvK1YOuR/tFN3NNyAd16r1au
            +vPBVaJdFHwfi8F/VOHVChPGqmrsKGWHqM0a4Twc3q9oWMZMHTZOFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-31T03:08:13Z"
    mac: ENC[AES256_GCM,data:fWf63+SwuqShjLGQ202mzOFCZ2fuuBZiBnhP6QY1UMulOpVI0codymU7u8LBYgYOLfPEJGl2vtXodpL0ke7jY3N42MJm+nZOzG+3N0HLqrKATHuIc8kxPwZ/HMOMXoaEY5T7AJu52cAy0TgzUD+yNFZgZH5NtaO9GmxafDtRTHk=,iv:bydimK/S7hZpl47Fol/2Khu1Dtb/46z82k2r/EXLqLA=,tag:qDB4SRH+nUalZ3g9vJz2jA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
