apiVersion: ENC[AES256_GCM,data:d98=,iv:Y/bE1nngShxw6Q/5gZ1583JyqDxV0Csz5qSluLljhx8=,tag:tsOU527GvM4NS5MJVX5UcA==,type:str]
kind: ENC[AES256_GCM,data:Or2Lhlph,iv:mMXDvPoHY90XVPmcN6AHNyocyez/6rnUf3nQ3erRVHU=,tag:LvWKEnEs3GyW8nf9h+8vbg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:9IxLycz/0Vn4+ZUxSwYuHu0sh20=,iv:t+5GQXSSjKuaW5vpo2nz1SDptPZbfHxXpXrnM1/DEvc=,tag:aZ25g3JTkVMx/Cy0mkwRlQ==,type:str]
    namespace: ENC[AES256_GCM,data:OK+T/6TPsUg=,iv:GmtEcK2SgtFc1fZbwV4AUjwwUqmOgQPs2gcFAgv91dY=,tag:hM+QVlQoPxRtiv7THjINoQ==,type:str]
type: ENC[AES256_GCM,data:2F2+1fNn,iv:bGE6i1LwI7ZoyDLJGLCM33a9wE1F9tKPJYvmIQtZRls=,tag:iXT3FGAZQ1R6VsNHfEbKyw==,type:str]
stringData:
    #ENC[AES256_GCM,data:Uo2QYMXkBXw6YMnyInW9uv4i7y52jwIlw1sZZkCKg8/ZEIAKpf1kj7y/ULqzca9Re82Wxz21DSJ6yLAIamMwaGphn82QoqsAYscwr5FpETSMUUEh6Q==,iv:Krsacwj6o9urW67uBlfkLI5P7E5sBAURlJHGT7oFOto=,tag:9I4f8lLQj04kZHpXR/scjQ==,type:comment]
    BOUNCER_KEY_traefik: ENC[AES256_GCM,data:TEJS4yvB6AMzENT/Wc/TJC7rLNY816XK3xqVNt9sIqmYHypPJtmKmdBWrYHvDOTakLRa+Brju/dXTI080A6Oyw==,iv:pEkYXvgayQPGHTKDuv18twd9AlQQ4yeajhOkQq54lY8=,tag:OXq0wG4E8i5xDzEcOU4mcA==,type:str]
sops:
    age:
        - recipient: age1wcyzl9vjwakzxtxzw2qupn5332q7kpe8j4zyz434dcx2frqwd58qeutllz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5TEt0WVdhNHJQb3hYRWZ5
            WTkzY0tXeDh3Yk1rR25MOW5vZ2NuR0ppQ1VvCnZ2a09wcitld2J3T29jeXprMXEx
            Vlp3clp3YkpZanU5RGZ3UHN3aUIwOTQKLS0tIDZVT0daVkpQWVFNaWtnaUk3ckEw
            aUoxQURCOUFYZ2ZyVnFYejVwakNlR00KQZluIjdx0UA3yIEsYIzIkHi3J95FvGs0
            c6r9x+qypEEzggUFIPUuY1LNQqM04bVMNO5ION1A+fUjH59QbXoTOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-30T23:48:59Z"
    mac: ENC[AES256_GCM,data:WDtYHSwzxAxg2UjO4qWY/AqAXrxHzDLWbZwTzHwZUrkG6AIxyGmcOVy06ZOm4kfbpIP54QBcmjO0VnZis6+rM4Wyq8PxggagaWvEY2oJy3pfoukYOmpnjveWO+3HddB0kTh5fOIq80tExhWP3hQoHwtgOkzi31084HmL04nTDTk=,iv:+LGN2NwnK8dxtVWH39GmK+Wez/KOY28WtsTd8O5quac=,tag:vbx57YiKoq+F2x5J+szzRw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
