apiVersion: ENC[AES256_GCM,data:pX0=,iv:Qhiqdq0bgr1tth18/5CkK/H7aiBs0WJ0jhiqHWzSSZw=,tag:+kkyrFVopoqOkh49U+B0bg==,type:str]
kind: ENC[AES256_GCM,data:JjKYpb13,iv:w4dfZFPb9KrlyWekwOh0FHo5feOYwAMGJd6NkpVnBjY=,tag:67N5TqHGEtK4451p+USYQQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:/tIkL95PTW1jgnXHK+6/a9w=,iv:JDwRJYjJ6eXfHCKhzfyBPBq9B5qX54lfHjsYTLhHYI0=,tag:vcvuGvADCMuZHJnfAEfnAg==,type:str]
    namespace: ENC[AES256_GCM,data:303Ob2Y=,iv:zorE9hJrDURL6DuAHi0LLjPbWbfqqPGAzf6UH4njiGA=,tag:l1RR/gEaDmKIvL+WJEZFwg==,type:str]
type: ENC[AES256_GCM,data:0McR6yaW,iv:Ho66sCohPmYFqKSOWDOvddmBbCv5dIRZdvyEom7CTJw=,tag:ka+ZRLs7UJTUM9qJYuq7Xw==,type:str]
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:uRkM/b7vlA6LGWVJ2m3G53YZyQQ=,iv:uOcfINcMXuccXDkdjAQ1Pz8UR+fm0a/t+ePwIqsWAA0=,tag:Jy2ObMYZX9Yf2ma1bsklZg==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:9h3ye72IXL4QLmP5ErAfx0lZ1RXGUNHCRpAww8Y0eNYgOCfMDRo0NA==,iv:CGQCffYhtitRMWrtvF/5r93ArXHIRPDl9bItIS2Rolc=,tag:dsouXeKDztJg8YP/SRXL/w==,type:str]
sops:
    age:
        - recipient: age1wcyzl9vjwakzxtxzw2qupn5332q7kpe8j4zyz434dcx2frqwd58qeutllz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnaHo2Ujk5VXIzc0tySWt5
            SjhoZ1VKYXltbXArZVc3ZzNPd3piRllYTWs4CmQrSXZZTDhKcDV5OUVxYkQ4RFRS
            RnZoQUdGY052ais2Z0ZxRWEvTUp1a3cKLS0tIE5Pd1JjRjk0b2o4T2tkVENuL0cv
            amtJOFNNSUxPamhKRTM0b2ZEY2l3T0kKYtbcQsKNwIcGBzVZXM4cie6oA8yHDAFN
            Df5/jRsGHeRQuQJnKoO2dTO8sAWLCzjlPV1HdHkBkPrh7kvUaKsBmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-23T23:54:21Z"
    mac: ENC[AES256_GCM,data:g4VP7mM1P8sUD6HYDPlXmR/opax5589K6OM1cAOLexrCflxVnJHjbvmb12lbQdF/XoQnWjOrZA7ezLYyQZx1xB4OZMNhaxtFG46Q9oSd+AEokKUlVamgE9uEP69CEm9BMJ2p7z/c330VSlgeOHKFmVsm2tuIMHn/HZHTCvl61hw=,iv:ciUFTGQRJJ2ALkymM2EBTTxLa3r+ODdEe9WoBpUVwik=,tag:xpDRRro81MPTrumddmudSQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
