apiVersion: ENC[AES256_GCM,data:1E8=,iv:v3tEw4V0sgLTcEa+CDn/5yPu1IoVtOXox+sQI1YybG8=,tag:MsPu8iR9C9gVMGuTQBWGvg==,type:str]
kind: ENC[AES256_GCM,data:3ibQEeoe,iv:mhkHP/BqnIuzQVF0BmvoWoc/VE/kmK9x2kVJSAYU4yI=,tag:tATf5oZcNdhFVRwP///NTQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:5xbCNqC5jNsfjZBV2y6r,iv:aWLCS71BR8/pyyCXu2rLn7AFC+uCiTyjAJ90o8lvwrc=,tag:dHg5KupEGOvSLNndBrEfRw==,type:str]
    namespace: ENC[AES256_GCM,data:zqMdtLM=,iv:RzwTlh526i+JW88JSmEnGWy92RyA2E7vM02cOKvNjVE=,tag:ip01ctm2VYmHmkBEbwssdw==,type:str]
type: ENC[AES256_GCM,data:cdFky67X,iv:+LTgkQkNyfCxbhBKArmUJAd4BUhFEmoR/hxEyYaCgxo=,tag:gXgcn8W+lqyBSGE0gKnviA==,type:str]
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:QQ0diECGObIa/2sx+uW71xK91yF5jxyYLDtI4Ps5LL9G4OdNZqD69zIqLZHRa2H1ZOE2Ikhmv5anoz2cdtePEg==,iv:E2BeLGIdSk7/RcCKogg8aXSNKDvIdVJ+L+cke/rR1fk=,tag:Ia52o0JHRfV71DcyNd/2Fg==,type:str]
    COOKIE_SECRET: ENC[AES256_GCM,data:w+ZaIPbiWNPeKb//E/PFlk0ZN+GvtMj8OxqoO1YRdQDOSavjtxxmfKfijRZc8ih3/fdwMEHmQcwdOwZgTzDS1w==,iv:kOI7C7zu/Z34NgM1RQRi0lnaSVu7bVToHoQspwYLQ+k=,tag:wuPhrqafg8DH2MsWSrPfqQ==,type:str]
sops:
    age:
        - recipient: age1wcyzl9vjwakzxtxzw2qupn5332q7kpe8j4zyz434dcx2frqwd58qeutllz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYYXdrUFJhYVdISHVLMXFX
            WWRuMHkxRTlVSmFRZWljSlIySGdHdGdLd1dFCkx6NnlhamtYUG1TQ3VQNXNEOTBo
            bVFSYVJNRCtvelUxSWRaM1RvcWNMczAKLS0tIG44R1ZtTjZsRUUyYUNqZmx2QXBL
            M3Fnd1ozdjJTSll2WkRDdm12WE5tV2MKS4tO2QSUjGcEZB0l0D7xAzKqhttOMcL2
            CrXnyGA1E65jiSL5mGors8hBjOw6/Pc9kz3q639pxr0sp6L/UWO17A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-23T23:03:11Z"
    mac: ENC[AES256_GCM,data:NJ19BYRSoe1Bw6wbTLZUS1m3KOp9HYWNjXRPJdyUZEvU93rCpOT1pdTv9rQ/NXOf2LmoRSxOhUIOGblq1fU6I6cWK0hX1zo2GyTRHxrQ/ZF6n0DrnYCOiPtS0QcTG1hK4Y6lelm2BJf2pIiprmknNDkXaJj8iqnTre4ySaoNW3E=,iv:d1PSTtkKqZseyuybXmYOSVyFpl73uX5aPVVX6Bd7bKo=,tag:vsdnq6wpXhvl0jmhec4F6w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
