apiVersion: ENC[AES256_GCM,data:RAQ=,iv:r0BG4/g+UPnwuROB97Naisv4/oPhYCJ+1l6Z8MeX9A8=,tag:3PMup/USqJUqF3fRnyxWUQ==,type:str]
kind: ENC[AES256_GCM,data:6fuqRM4Z,iv:V2ZDeBP9yb7SczevgxrYGibleUgZoEhEJ72AIt/2qj0=,tag:+yxw4yrm2FvVj0fkPylc5w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:7NFxa2+q5Ft9Uctr0yNVtmQH0w==,iv:zWveT5fG99zA5fPWKR3T+RiIlzZ98vUHORgMio/AsM4=,tag:jafeakP6jV+OM89BSn4WMA==,type:str]
    namespace: ENC[AES256_GCM,data:K648bSA=,iv:WKFqZ5KBN9J0tP8uo4wNIP+fiiKSolUJ2ORmXnzkAW4=,tag:WO7VGayYkzuzVe1tXW1uBQ==,type:str]
type: ENC[AES256_GCM,data:mYIGaKRI,iv:67dpM8WOidko6L3SY5wimdI52rAIJtkgWnyiBIlljOY=,tag:AoVt+JzpOqc1yZQQVl7+Xg==,type:str]
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:RPluKV7h8BPtRaFXHdFF+NXcjC8flBMyE5Xsxg==,iv:R+hEYm+JhhNXfT6C/Q21og630PrQWKXMRtONc3sYkPM=,tag:IWzzGochEClzns0DJys3cw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:HDrzxRdqL8Jp3jfbH1PAIgOCf1u1AJJSM4XrMUzblx0qtq4wCKEUdzObV74XyzDZQcNcVNJ2qdQ=,iv:C3aYCm1+s6DvZ7y54UUkIt6x83tMYTY2fugXbleIwv4=,tag:iilQlIPKRyct3fj2Dd6wqQ==,type:str]
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:2APOv1YcIMQEl9IjHM2jLoFpGBDNMwYYwtQizNcVtpGU3jKVfkPtHg==,iv:kkaoEHtG9dHAteoUWEZO2SdLb2tZcGUJZpUH7Xb0Xvc=,tag:/0A/C0JcU5pzMJ/iuhsbYg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:1q8sLjF3MmjsXgOb0pLNLpgBgVl9s4bIDa4r8SGJ3wcwKLa7B3JJDjYOTHs=,iv:vwSi7sDL+klX7W99Bou1B/2hJEYd/R5rc1FM6jviHWA=,tag:T6ZuxbQYiH5wrtKMnutbag==,type:str]
sops:
    age:
        - recipient: age1wcyzl9vjwakzxtxzw2qupn5332q7kpe8j4zyz434dcx2frqwd58qeutllz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnSlRHRmNjZDB5dmdWeXpZ
            ZUJYaDNsQjZJYytFTVREWFptZ3dVcklmRERnCm1LWWJVdzB1K3F5cW1GdjJoMXlH
            MERpTjRxZGxPVzJ6QkY0TEExKzBRWTQKLS0tIEN6aHRiUFMzdkJBVExkM1RCVEgw
            MGNNUW5jV3FDOGJTNEU0cjJSS0xYVm8KeXM6pR4x4C4stn27J7AM4pY7iPF6O4Ib
            LKQ37atkHsavcTTmfckUrslQZFW1DlJ3pHxQ5OVKFmDaIQ7ErmWnew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-09T12:59:51Z"
    mac: ENC[AES256_GCM,data:hUXxGg/5c22oMxR4Mufj2yksj3ZlOSsH3KPybPseDKUkFOOfZmvbHRUb7qrSmyNn05gG3O/Xx5Br1zy73DfuFevOg+lDYmL1Dob2P83A9nrTn0coCpOQl7VTcwOj9mIO6t5pfU2X82cBffucFKTL2M/A9Rjgr4YYSdA6WyX0sFo=,iv:EHSLpQ4VCKeJZzkeHBU2rpGk3ewoW4Jz3BMmT8VtoDc=,tag:4VRglMa+pP/D2NJ5pjoq9A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
