apiVersion: ENC[AES256_GCM,data:VKU=,iv:zmxpXd2Wu7DaH5OxcEWivB3B8Kh07xuEa9Ob8NHLwxw=,tag:ENXmvS7XOZBN1Wr3iqWNMw==,type:str]
kind: ENC[AES256_GCM,data:hQS/QfCp,iv:OxEkaqELsJKzNvzlcZI9GzCtqbywYL3qeGc6e1vmKh4=,tag:2uWBIVI49uA2n5AxmFV+7g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:0UTuzphn5LytksIF,iv:rKguKQzXgUjCAb+kOmXldq1p3E4gzTg13O0Uixm+I8o=,tag:7ondyFSjcR0+naMrSU+AOA==,type:str]
    namespace: ENC[AES256_GCM,data:h0NCqGs=,iv:jZp/UywzIdbM/dlUteM3Uz0cWUkBUI/OldSSGM3xg7A=,tag:MqqXUSgs+479GFNJgP3bEg==,type:str]
type: ENC[AES256_GCM,data:JzFY4Pf9,iv:qcV4S4Si5q0MJ5w8R5Pgshqv0O1NXLdoCYHvb9ZKSIs=,tag:kmM6lSG+afE6w+UnIxxOSA==,type:str]
stringData:
    GITEA_ADMIN_USERNAME: ENC[AES256_GCM,data:pcKq9s8=,iv:hbH7Gk7YKzrwtkfBqYhRgNPi6XEFVL35dRRXbP7CNWU=,tag:ugsVwj9jtn4UreUtNfpIWw==,type:str]
    GITEA_ADMIN_EMAIL: ENC[AES256_GCM,data:6FjC/01+W9IREUD+U+Shce4YOdYmYrg=,iv:Q5paL8dRR7XdJvm/i0yV2VrUVzbZVRhksUslFqS4As4=,tag:sdVihqD/j6metMP5P6hEeQ==,type:str]
    GITEA_ADMIN_PASSWORD: ENC[AES256_GCM,data:Ux0rPg1lMsIp/dkuzZ9xxxN4XszidencIKhhDfoOP2Y=,iv:mSnBj2pBzALOgE0aVy3gd/XSHLK9FiItDYRJ7ydn2r8=,tag:FakSL8DKz9lCPVE73qdQSQ==,type:str]
    GITEA_OAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:zqNB0MMsVW90BAC9+OH6N7kzrtUbfFPzAZxOvJs0NLl8180jS1IG4rlSIKIPFTtcNU7XJm4ix5xQJgcsgMLKlw==,iv:8hAEuwoYIzTbzSzOomv2P0l7l3hoeRfaFbATbNfBVcI=,tag:ERk8YrNXtTE/mggh7ULT1Q==,type:str]
sops:
    age:
        - recipient: age1wcyzl9vjwakzxtxzw2qupn5332q7kpe8j4zyz434dcx2frqwd58qeutllz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZFpxbFRyUXFzZzd6QzNJ
            WnFXOTR0VUQ2SmprZWEzTkVYTUNHa1VFN0FRCm52OC93VmZ6cjB5Q3cyczZnQ05Z
            RFcrSjJCNW95bGM4NTZ2Z1FwS2kwR1EKLS0tIDBxZkxJSWdjeVNtMms3SDU4RFlY
            MFBDcExwdjZrL1BWbElqbFBLN1JiK1EKjeyeO7zNgjCjleUhBlDdmbdrZkstAbVU
            Sjwvvby1oCiCLbXhIa0X3jsRv7pag7uVj/2S/qAXQBykEkoRTs+luQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-09T12:59:51Z"
    mac: ENC[AES256_GCM,data:30Wsx0OcSg8kRIxVaFbLDTKDaL2+f+vJQwSixFuJxNdDyf002VFVDYmmPIN3Wfyz554VXVrRU3s/zpAENqSFYR/m3Q79DWIENQMekkf7A9+VCbQwrtuZAY2Ifi/MZQBnc6sFIlKMFmEbEtC0zbiROVtH3z/iRUkXJcsm1qezw4E=,iv:S6ZsnE7jWjodAHdnMMM3MtNEASeBnr3Of303UnUeKwo=,tag:SN2CY7sg4y5SXPBhIxikuw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
