---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: maintainerr
  namespace: media
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - maintainerr.int.nerdbox.dev
      secretName: maintainerr-tls
  rules:
    - host: maintainerr.int.nerdbox.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: maintainerr
                port:
                  number: 6246
