apiVersion: ENC[AES256_GCM,data:tpA=,iv:Vz8MPthxr5JxM1KzOV7bHlxsqOBarBPGksAh0jlqn+8=,tag:qCVYYI/bEa8I9Jm9dvrWMQ==,type:str]
kind: ENC[AES256_GCM,data:Hkzeprdx,iv:GNte/zKIcnbJDu54tdtUKX/O45KbkcCW3YDuPottcwM=,tag:wQcGHBnE5+7KJI5DaA2f1A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:6oAwbLOjoyOtdODPg6EV4Ovb2Yc=,iv:bV1UPH2XHV+BjJVO2vkByMi7zRGB4aqLPtLdOEtHzVI=,tag:ASgmnfA+L3Az07QpIoXUcQ==,type:str]
    namespace: ENC[AES256_GCM,data:FV0+qGk=,iv:XqdIc51AQij/g9xfC+lfAA61MZH6Wf7WJ5wr+X0VEao=,tag:hIF5SYSSsktjOKRpCBOQzw==,type:str]
type: ENC[AES256_GCM,data:gigCW7JP,iv:7Zogg0RFsAeMTpJ/WuQBh57m2Hd8DCyirCQ5M+dDz40=,tag:lYVfkLIBoEaMVpkzTozVYQ==,type:str]
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:XNploZZblFKTwF6nrjV5MgRtd/8kRSKvmi2RPgDzNxVGNKGIyh1Dsok=,iv:tb9VzkeQWYIBR5L3AwD9NC0S6e0yBSRcG1e1ZKgdNyc=,tag:4XmIo/QwsM8219CljFA0GA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:fxTJiRqjma43w/BLr2ISdQaDL2RWUPRV8OpJZhyEO9HjzpH9KizqZ1tmlehLu2qESjp7I/SKAfGF9g9ERN5pAw==,iv:hPeXdq6Jk2c3m5eKSvHpdK0D/8f+HhJ71lJPuosSFSE=,tag:bloGVpqNPO3V8LUq1NHpJw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:fL2NoBgwftrVyKOdh7ytaiTu1sE=,iv:jbkeFuSWwkoo7GsGRAGNspf+CFhK0x9JEEYhHoKZBNI=,tag:MFc5eqqZvjHfkFlwXPpjLg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:1klfpEZXdLugLq9VaxF/C1ZatBYvd7U6YpIqJteyGP4bz5HjnmaojQ==,iv:CEZWnOvIvsDZQpL2G8COUY7zkGGiP8ZZtOeMqAND+UU=,tag:Unzy9QbE+LT683In05mK8w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbW5GRHBRS2s4bEgvR2Va
            dTlDZ0g3V1NsNWlzN1RlRmlNdThHOWFKblFBCmc4bTk2SmJLZWl4NzFxS2RmcU45
            NXA4T0NYc2NkOFFRemJ0enJtRmRrREEKLS0tICtOelk5VFpoWk44UTdoRWUyV09D
            Y2c3cG1YKy8rSC85dlk2bnlWY0pGZjQK9manDc6XAmyZ5oZ5mjJcJeh1VPR1DiS4
            B3/AixEedqkMxyK3WSqdQkylFkCMjoE/y4DLsY+aP9xT2e1uQrOXcQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wcyzl9vjwakzxtxzw2qupn5332q7kpe8j4zyz434dcx2frqwd58qeutllz
    lastmodified: "2026-08-09T01:36:48Z"
    mac: ENC[AES256_GCM,data:KOFfVB0JjEWGDIi8ZH2d+dXW3o5prBPxKMWdV9r9l0qRKweNCd9BZ3WXUkqwyLVofKEZjwtWUHua6sa4Xl3NOY6N2HkCoNck6TxBCplE8NW2b4f5FD+b4yuu7j4qiXueBgMmem5TkYA4LdLwIiJzHu6hAet/jvQ1chh4BVYCe2Q=,iv:ztowf5/+zFSEoGVwbidv5s1qj84xWKrsWCtX7wL+MZk=,tag:sYqjKugW4J0U8F9U/qKoMQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
