apiVersion: ENC[AES256_GCM,data:ZlM=,iv:InRlyHGAxdnNT4QsF5tVPTXB3WdRh8/lnkm4aMoeumI=,tag:TNl0oMvZI8FsCd7cAX3D8A==,type:str]
kind: ENC[AES256_GCM,data:pam+sLt8,iv:5JfPnFhk4OR+/W0dur+m6LNY0UZ7TjRnJpdWbo9lobo=,tag:AOV0OJxqtKyLbSXaY5sEBw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:w81KbyalvKjug2RxQ0/tAkd3fwMwHrcldw==,iv:It1pdabl3rXYyaI+u/zpoHelgSPDwxj/71d7ljJZE/8=,tag:KigZR7WEf1b+Uk59fmAjHg==,type:str]
    namespace: ENC[AES256_GCM,data:bzoRBSI=,iv:eMZ7F8eB9XUdmccTsxs3tAHQXLsjKQmHV2LJnSmpwHA=,tag:4QRc+vWvB4EZow1PN8SbsA==,type:str]
type: ENC[AES256_GCM,data:sJcHZrR4,iv:3MaXf/6znmnnj4YobdgU8KoWip5O6FgpL/RIBkgKrXY=,tag:u8avnB3APb0lJnLi55wtlQ==,type:str]
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:XP/7UxuCFA7mlZ3j043f/4RhXB0nws3ihV8Ye1YDDALkPIph0oyem3pGjAwmYQ==,iv:cXdxc4MlafWRDnMNrCw8ixdDVr/9U59HsBlf5sjyI7c=,tag:CSLj0P1E7d9qDf4PCe53lQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:HTKDzX+e85Bz2N4kwy8vQHmH/htBWjbjOBARuKWZCF5QfwtJSdNHzKAS1MHrAaMe9Kz1maq1vjHcDvX8Ps7xMQ==,iv:jfmVeOzJg1MqNGweDX3xkbCkVcA+jlEr9Zu6M0/Lprs=,tag:PETUumGEqRh05wvZg4/eYg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:shbfpF4mp5Ds7kyFerRtDecs09w=,iv:rxkCOwtt3A7hEtO3BIXpi1/oth/PEHU1xDGINZ8ympQ=,tag:++WEBCLX+O8pPjnZySERiw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:fLPHLAz5FIJWhpjUgfS5prMM9vI2qsoN1FuyF+9IHTS6aaUQpsNc+Q==,iv:syXuQuZ60yJyHNr2QPOr4JpgEUvKsIl/283CkfyQvF0=,tag:nfcfLzbifbfDqzxsy09DMg==,type:str]
sops:
    age:
        - recipient: age1wcyzl9vjwakzxtxzw2qupn5332q7kpe8j4zyz434dcx2frqwd58qeutllz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQXVZMGRUQllHa3NUclZO
            d2R2Q1d6aFZPM1pQT3hBVDcwU2lSMk9aWWs0CmNSKzE2a3VWbmVSNDJoVnhMSDNk
            L1FxMDJsakM4NGFIR0tPRUZ1eExMNlEKLS0tIFdka2gzVGQyOVdxMFpQUmFMRXE4
            VmdmSVBnZUpNOEJGSVZPTzM2aXZqak0KUP1w9HaCasWihH3nDbKmL4grGHoYqvD5
            UbXQTSim3YolDd3BixfHdvm6uIyo/5AbFNcG1c6HkC8Gbf9/fusqjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-26T01:39:02Z"
    mac: ENC[AES256_GCM,data:phjo2f+K+A4HL0C4PkNbHg9YEcYAdouKRsXBR/Ah9TlTvDXr2wIDhyzqptBChejrhnKqcZMH7FQwnL0/cEVhMLD0lQL6JgdUy5i/hJKbhBYvifp2tpJWpwURyO6FWhNXpndkkIuWq0UjP1e49FWQ/RNpu8RhVgmsFFiY3UoMFoI=,iv:qly2sCbwWNxbsNkk5hyp5Dftd9czWJ8TSDneqm1eyCg=,tag:/OJHrMoVwA1s3C/ODCbjzg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
