---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: prowlarr-config
  namespace: media
spec:
  sourcePVC: prowlarr-config
  trigger:
    schedule: "10 3 * * *"
  restic:
    repository: prowlarr-restic-secret
    copyMethod: Direct
    cacheCapacity: 1Gi
    cacheStorageClassName: longhorn-single
    pruneIntervalDays: 7
    retain:
      daily: 7
      weekly: 4
      monthly: 3
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
