apiVersion: ENC[AES256_GCM,data:ZlM=,iv:InRlyHGAxdnNT4QsF5tVPTXB3WdRh8/lnkm4aMoeumI=,tag:TNl0oMvZI8FsCd7cAX3D8A==,type:str]
kind: ENC[AES256_GCM,data:pam+sLt8,iv:5JfPnFhk4OR+/W0dur+m6LNY0UZ7TjRnJpdWbo9lobo=,tag:AOV0OJxqtKyLbSXaY5sEBw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:BxzJ7G4CUSZ7T0Gf4dErM6zy+igRUT7BIw==,iv:sjGzlX4ueoHoBvlkQ1qiDxQnu9Neya6Do3MIxyDgcQY=,tag:GyJnUwf74cxsS2tsOVL2jA==,type:str]
    namespace: ENC[AES256_GCM,data:bzoRBSI=,iv:eMZ7F8eB9XUdmccTsxs3tAHQXLsjKQmHV2LJnSmpwHA=,tag:4QRc+vWvB4EZow1PN8SbsA==,type:str]
type: ENC[AES256_GCM,data:sJcHZrR4,iv:3MaXf/6znmnnj4YobdgU8KoWip5O6FgpL/RIBkgKrXY=,tag:u8avnB3APb0lJnLi55wtlQ==,type:str]
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:py9Deu8khd5f/Zl/0BJkjHXlL85Pzg+TcW2mOrJT63YOPJKy1tQqeA+edOWlVQ==,iv:K1VoegxbNvMOa/ellCg541VHMDqnEHkKYydwoGJKx+0=,tag:a3WQu6FjNLWwvPOtPeuiVQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:HTKDzX+e85Bz2N4kwy8vQHmH/htBWjbjOBARuKWZCF5QfwtJSdNHzKAS1MHrAaMe9Kz1maq1vjHcDvX8Ps7xMQ==,iv:jfmVeOzJg1MqNGweDX3xkbCkVcA+jlEr9Zu6M0/Lprs=,tag:PETUumGEqRh05wvZg4/eYg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:shbfpF4mp5Ds7kyFerRtDecs09w=,iv:rxkCOwtt3A7hEtO3BIXpi1/oth/PEHU1xDGINZ8ympQ=,tag:++WEBCLX+O8pPjnZySERiw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:fLPHLAz5FIJWhpjUgfS5prMM9vI2qsoN1FuyF+9IHTS6aaUQpsNc+Q==,iv:syXuQuZ60yJyHNr2QPOr4JpgEUvKsIl/283CkfyQvF0=,tag:nfcfLzbifbfDqzxsy09DMg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQXVZMGRUQllHa3NUclZO
            d2R2Q1d6aFZPM1pQT3hBVDcwU2lSMk9aWWs0CmNSKzE2a3VWbmVSNDJoVnhMSDNk
            L1FxMDJsakM4NGFIR0tPRUZ1eExMNlEKLS0tIFdka2gzVGQyOVdxMFpQUmFMRXE4
            VmdmSVBnZUpNOEJGSVZPTzM2aXZqak0KUP1w9HaCasWihH3nDbKmL4grGHoYqvD5
            UbXQTSim3YolDd3BixfHdvm6uIyo/5AbFNcG1c6HkC8Gbf9/fusqjQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wcyzl9vjwakzxtxzw2qupn5332q7kpe8j4zyz434dcx2frqwd58qeutllz
    lastmodified: "2026-08-04T17:13:38Z"
    mac: ENC[AES256_GCM,data:K98VXWtZGq1fSSQeA0Eu9YYW0t9dC6mnAE06ToTcHQ1b9bhA/w2CYePYWKdwNxnkx8ymT4AmUewHzycg47Eu8siSjS04oIhlzowkZTr+DcqMKslhqMmY9ue9ZKg1kBlBeY5ef9Zrdui4xFyUBYufCYgW7auKL13ELEW81l1msk4=,iv:F3cCGnlOwLT3TfBclSV2vHgYr8+O7KDyJg038d4nTaI=,tag:e7EWssZSymluIHmdhSSv3w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
