apiVersion: ENC[AES256_GCM,data:tpA=,iv:Vz8MPthxr5JxM1KzOV7bHlxsqOBarBPGksAh0jlqn+8=,tag:qCVYYI/bEa8I9Jm9dvrWMQ==,type:str]
kind: ENC[AES256_GCM,data:Hkzeprdx,iv:GNte/zKIcnbJDu54tdtUKX/O45KbkcCW3YDuPottcwM=,tag:wQcGHBnE5+7KJI5DaA2f1A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:sYWXetUq0L+fbK+4hGK+jFJkneptIw==,iv:eKYl0EdtXQE2zU8rNMYxOTg551rMRUAeOBF0VFL4qLA=,tag:nwcYJoEHhpUzoRFbyHK1lg==,type:str]
    namespace: ENC[AES256_GCM,data:FV0+qGk=,iv:XqdIc51AQij/g9xfC+lfAA61MZH6Wf7WJ5wr+X0VEao=,tag:hIF5SYSSsktjOKRpCBOQzw==,type:str]
type: ENC[AES256_GCM,data:gigCW7JP,iv:7Zogg0RFsAeMTpJ/WuQBh57m2Hd8DCyirCQ5M+dDz40=,tag:lYVfkLIBoEaMVpkzTozVYQ==,type:str]
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:fiphUpsdaFxyrtpq3XD9invcb3gsOu6GvVNRURfGJSCBGXpWiDQvbaqSVw==,iv:OOsluzKcRNZU1lH71zbqCp+CY/nRsU4l4I7xCV/90Jw=,tag:rNfsMmwedD48EsvlzRpuoQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:VaUiCZZERasBxxQK5YN6x7rb/GvC5yX7JYjwGH+0iiN7X9/Tsx9QPT1Gb/S/G31EWVIw9RcSFe1hvzol562KjA==,iv:ql0vwGASn66ZjitH/F70pa2QAP1f9l052WXVyPxtB0c=,tag:rU45ujDzOpCHBBwCN/E4Yw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:fL2NoBgwftrVyKOdh7ytaiTu1sE=,iv:jbkeFuSWwkoo7GsGRAGNspf+CFhK0x9JEEYhHoKZBNI=,tag:MFc5eqqZvjHfkFlwXPpjLg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:1klfpEZXdLugLq9VaxF/C1ZatBYvd7U6YpIqJteyGP4bz5HjnmaojQ==,iv:CEZWnOvIvsDZQpL2G8COUY7zkGGiP8ZZtOeMqAND+UU=,tag:Unzy9QbE+LT683In05mK8w==,type:str]
sops:
    age:
        - recipient: age1wcyzl9vjwakzxtxzw2qupn5332q7kpe8j4zyz434dcx2frqwd58qeutllz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbW5GRHBRS2s4bEgvR2Va
            dTlDZ0g3V1NsNWlzN1RlRmlNdThHOWFKblFBCmc4bTk2SmJLZWl4NzFxS2RmcU45
            NXA4T0NYc2NkOFFRemJ0enJtRmRrREEKLS0tICtOelk5VFpoWk44UTdoRWUyV09D
            Y2c3cG1YKy8rSC85dlk2bnlWY0pGZjQK9manDc6XAmyZ5oZ5mjJcJeh1VPR1DiS4
            B3/AixEedqkMxyK3WSqdQkylFkCMjoE/y4DLsY+aP9xT2e1uQrOXcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-26T22:05:14Z"
    mac: ENC[AES256_GCM,data:25U6QhE92NGOavTuLzi7fwuefJEKCyZSDUoRJOwezEk0FrPAfdEbxNPs7Cy/IOCsD7cgl0GDv7U9lwofBUyQ895+cSf82hJfTDVuAszuBegxy8iCcAvu33/ZXjJ8HAMdf8lHalNxUhxAizogDOk6wVkHlKS+geZHkSCK5aGMUko=,iv:hpwls2smxad2mF7lAtuuMrZDGCGL8J+2FwLfxhdr0ek=,tag:5xf40ZYMfwDUeVzpTnTZdQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
